const {test}=require('node:test'),assert=require('node:assert/strict');
const {compare,service,inventory,SITE}=require('../tools/apple-caldav-production/functions/lib/monitor.cjs');
const {buildCalendar}=require('../netlify/functions/apple-calendar')._test;
const now=Date.parse('2026-09-22T21:30:00Z');
function data(){const rows=[{id:'a',date:'2026-09-23',start_time:'10:00:00',duration_min:60,status:'prenotato',service_id:'pt11',client_ids:['c'],operator_id:'p'}],clients=[{id:'c',nome:'Test',active:true,sessions_total:8,sessions_remaining:8}],operators=[{id:'p',nome:'Trainer',active:true}];const full=buildCalendar(rows,clients,operators).body;const e=full.match(/BEGIN:VEVENT[\s\S]*?END:VEVENT/)[0].replace('END:VEVENT','X-NEACEA-LINK-ID:m\r\nEND:VEVENT');return {rows,clients,operators,mappings:[{id:'a',uid:'a@calendar.neacea.it',marker:'m',href:'a.ics',stage:'linked'}],events:[{href:'a.ics',ics:'BEGIN:VCALENDAR\r\n'+e+'\r\nEND:VCALENDAR'}],lastRun:{at:new Date(now).toISOString(),failures:[]},now,cal:{url:x=>x}};}
test('aligned event and arbitrary manual Apple events are quiet',()=>{const d=data();d.events.push({href:'manual.ics',ics:'BEGIN:VCALENDAR\r\nBEGIN:VEVENT\r\nUID:manual\r\nSUMMARY:Personal con cliente\r\nEND:VEVENT\r\nEND:VCALENDAR'});assert.deepEqual(compare(d).issues,[]);});
test('detects missing, duplicate, slot, display, identity, stale worker, source removal and pending links',()=>{for(const change of [d=>d.events=[],d=>d.events.push({...d.events[0],href:'copy.ics'}),d=>d.rows[0].start_time='11:00',d=>d.events[0].ics=d.events[0].ics.replace('Trainer','Changed'),d=>d.events[0].ics=d.events[0].ics.replace('LINK-ID:m','LINK-ID:foreign'),d=>d.lastRun.at='2026-09-01',d=>d.rows=[],d=>d.mappings[0].stage='pending',d=>d.mappings=[]]){const d=data();change(d);assert.ok(compare(d).issues.length);}});
function memory(){const map=new Map();let version=0;return {get:async k=>structuredClone(map.get(k)?.data||null),getWithMetadata:async k=>structuredClone(map.get(k)||null),setJSON:async(k,data,o={})=>{const old=map.get(k);if(o.onlyIfNew&&old||o.onlyIfMatch&&old?.etag!==o.onlyIfMatch)return {modified:false};const etag=String(++version);map.set(k,{etag,data:structuredClone(data)});return {modified:true,etag};},map};}
function fixture(){const d=data(),store=memory();let time=now,failed=false,mailFailed=false;const emails=[];const syncStore={list:async()=>({blobs:[{key:'mapping/a'}]}),get:async k=>k==='last-run'?{...d.lastRun,at:new Date(time).toISOString()}:d.mappings[0]};const cal={url:x=>x,base:'base',verify:async()=>{},request:async()=>({status:207,text:async()=>'<d:multistatus xmlns:d="DAV:" xmlns:c="urn:ietf:params:xml:ns:caldav">'+d.events.map(e=>'<d:response><d:href>'+e.href+'</d:href><d:propstat><d:prop><c:calendar-data><![CDATA['+e.ics+']]></c:calendar-data></d:prop><d:status>HTTP/1.1 200 OK</d:status></d:propstat></d:response>').join('')+'</d:multistatus>'})};const db=async(t,o)=>{assert.equal(o.method,undefined);if(failed)throw Error('unavailable');return {appointments:d.rows,clients:d.clients,operators:d.operators}[t];};const s=service({env:{CALDAV_MONITOR_ENABLED:'true',SITE_ID:SITE,CONTEXT:'production',RESEND_API_KEY:'test'},db,store,syncStore,cal,now:()=>time,fetchImpl:async(u,o)=>{emails.push(o);if(mailFailed){mailFailed=false;throw Error("timeout");}return {ok:true,json:async()=>({id:'sent'})};}});return {d,store,s,emails,advance:(ms=180000)=>time+=ms,fail:()=>failed=true,failMail:()=>mailFailed=true};}
test('bulk REPORT parses calendar data and inspection makes no business writes',async()=>{const f=fixture();const result=await f.s.inspect();assert.equal(result.checked,1);assert.deepEqual(result.issues,[]);});
test('new deployment is read-only; anomaly confirmed twice; duplicates quiet following day; resolution resets',async()=>{const f=fixture();assert.equal((await f.s.run('deploy')).verified,true);f.d.rows[0].start_time='11:00';assert.ok((await f.s.run('deploy')).confirming>0);assert.equal(f.emails.length,0);f.advance();await Promise.all([f.s.run('deploy'),f.s.run('deploy')]);assert.equal(f.emails.length,1);f.advance(86400000);await f.s.run('deploy');assert.equal(f.emails.length,1);f.d.rows[0].start_time='10:00';f.advance(86400000);await f.s.run('deploy');f.advance(86400000);f.d.rows[0].start_time='11:00';await f.s.run('deploy');f.advance();await f.s.run('deploy');assert.equal(f.emails.length,2);});
test('unreadable sources produce incomplete check rather than false all-clear',async()=>{const f=fixture();f.fail();const r=await f.s.inspect();assert.equal(r.checked,0);assert.match(r.issues[0].code,/incompleto/);});

test("uncertain email retries identical payload/key after lease, without duplicate logical mail",async()=>{const f=fixture();await f.s.run("d");f.d.rows[0].start_time="11:00";await f.s.run("d");f.advance();f.failMail();await assert.rejects(f.s.run("d"),/timeout/);f.d.rows[0].start_time="12:00";f.advance();await f.s.run("d");assert.equal(f.emails.length,2);assert.equal(f.emails[0].body,f.emails[1].body);assert.equal(f.emails[0].headers["Idempotency-Key"],f.emails[1].headers["Idempotency-Key"]);});

test('CalDAV properties may use separate success blocks and calendar-data attributes',async()=>{
 const cal={base:'base',url:x=>x,verify:async()=>{},request:async()=>({status:207,text:async()=>'<d:multistatus xmlns:d="DAV:" xmlns:c="urn:ietf:params:xml:ns:caldav"><d:response><d:href>a.ics</d:href><d:propstat><d:prop><d:getetag>x</d:getetag></d:prop><d:status>HTTP/1.1 200 OK</d:status></d:propstat><d:propstat><d:prop><c:calendar-data content-type="text/calendar"><![CDATA[BEGIN:VCALENDAR\r\nEND:VCALENDAR]]></c:calendar-data></d:prop><d:status>HTTP/1.1 200</d:status></d:propstat></d:response></d:multistatus>'})};
 assert.deepEqual(await inventory(cal),[{href:'a.ics',ics:'BEGIN:VCALENDAR\nEND:VCALENDAR'}]);
});
