const {test}=require('node:test'),assert=require('node:assert/strict'),crypto=require('node:crypto');
process.env.PT_ACCESS_SECRET='SIM_SESSION';process.env.SUPABASE_SERVICE_ROLE_KEY='SIM_SERVICE';
const {handler}=require('../netlify/functions/calendar-activity');
const {verify}=require('../netlify/functions/lib/calendar-audit-auth');
const token=(id='pt',level='pt')=>{const p=Buffer.from(JSON.stringify({operatorId:id,email:id+'@example.test',accessLevel:level,exp:Date.now()+60000})).toString('base64url');return p+'.'+crypto.createHmac('sha256',process.env.PT_ACCESS_SECRET).update(p).digest('base64url')};
const event=body=>({httpMethod:'POST',body:JSON.stringify(body)});
function mock(actor='pt') {const calls=[];const saved=global.fetch;global.fetch=async(url,options)=>{const body=options.body?JSON.parse(options.body):null;calls.push({url,body,method:options.method});const value=url.includes('operator_effective_roles')?[{operator_id:actor,email:actor+'@example.test',active:true,legacy_roles:[actor==='owner'?'owner':'PT'],system_roles:[]}]:[];return {ok:true,status:200,text:async()=>JSON.stringify(value)}};return {calls,restore:()=>global.fetch=saved}}
test('signed session is required; modified payload and expiry rejected',()=>{assert.ok(verify(token()));assert.equal(verify(token()+'x'),null);assert.equal(verify(''),null);const p=Buffer.from(JSON.stringify({operatorId:'pt',email:'pt@example.test',exp:1})).toString('base64url');assert.equal(verify(p+'.'+crypto.createHmac('sha256','SIM_SESSION').update(p).digest('base64url')),null)});
test('browser cannot supply actor name/email/role/source/correlation ID',async()=>{const m=mock();try{const result=await handler(event({accessToken:token(),operation:'save',actor_name:'FORGED',actor_email:'FORGED',actor_role:'owner',source:'system',request_id:'FORGED',payload:{appointment:{id:'a'}}}));assert.equal(result.statusCode,200);const call=m.calls.find(c=>c.url.includes('calendar_audit_write'));assert.equal(call.body.p_actor_id,'pt');assert.equal(call.body.p_actor_role,'pt');assert.equal(call.body.p_source,'calendar');assert.ok(!JSON.stringify(call.body).includes('FORGED'))}finally{m.restore()}});
test('PT cannot read logs; owner can read; no delete/update log operation',async()=>{let m=mock();try{assert.equal((await handler(event({accessToken:token(),operation:'list'}))).statusCode,403);assert.equal((await handler(event({accessToken:token(),operation:'delete_log'}))).statusCode,400)}finally{m.restore()}m=mock('owner');try{assert.equal((await handler(event({accessToken:token('owner','owner'),operation:'list',filters:{source:'calendar'}}))).statusCode,200);assert.ok(m.calls.some(c=>c.url.includes('calendar_audit_read')))}finally{m.restore()}});
test('current role and identity rechecked, despite valid signature',async()=>{const m=mock('other');try{assert.equal((await handler(event({accessToken:token(),operation:'save'}))).statusCode,401)}finally{m.restore()}});

test('studio gateway rejects PT and nutrition roles, accepts only verified owner and ignores forged actor',async()=>{const studio=require('../netlify/functions/studio-calendar-activity').handler;let m=mock();try{assert.equal((await studio(event({accessToken:token(),operation:'client',actor_role:'owner',payload:{rows:[{id:'test'}]}}))).statusCode,403)}finally{m.restore()}m=mock('owner');try{assert.equal((await studio(event({accessToken:token('owner','owner'),operation:'assignment',payload:{clientId:'test',trainerId:'pt',actor_name:'FORGED'}}))).statusCode,200);const call=m.calls.find(c=>c.url.includes('calendar_audit_write'));assert.equal(call.body.p_actor_id,'owner');assert.equal(call.body.p_actor_role,'owner')}finally{m.restore()}const original=global.fetch;global.fetch=async()=>({ok:true,text:async()=>JSON.stringify([{operator_id:'pt',email:'pt@example.test',active:true,legacy_roles:['Nutrizionista','Valutazioni'],system_roles:[]}])});try{assert.equal((await studio(event({accessToken:token(),operation:'session'}))).statusCode,401)}finally{global.fetch=original}});

test('new appointment null snapshot is omitted; non-null expected version is preserved',async()=>{const m=mock();try{for(const expected of [null,{id:'a',status:'prenotato'}]){const result=await handler(event({accessToken:token(),operation:'save',payload:{appointment:{id:'a'},expected}}));assert.equal(result.statusCode,200);const p=m.calls.filter(c=>c.url.includes('calendar_audit_write')).at(-1).body.p_payload;if(expected===null)assert.ok(!Object.hasOwn(p,'expected'));else assert.deepEqual(p.expected,expected)}}finally{m.restore()}});
