const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto');
const {PGlite}=require(process.env.PGLITE_MODULE||'@electric-sql/pglite');
const model=require('../app/calendario-studio/js/pt-session-model');
const sql=name=>fs.readFileSync(path.join(__dirname,'../supabase/migrations',name),'utf8');
for(const json of [false,true])test(`PT pairs atomic persistence, independent cycles, absence charges and renewal (${json?'JSONB':'SQL arrays'})`,async()=>{
 const db=new PGlite();
 try{
  const helper=fs.readFileSync(path.join(__dirname,'helpers/calendar-postgres.cjs'),'utf8');
  await db.exec(helper.match(/await client.query\(`([\s\S]*?)`\);/)[1]);
  await db.exec(`alter table clients add column package_frequency text,add column giorni_settimana jsonb,add column importo numeric,add column stato_pagamento text,add column tipo_servizio text,add column stato_abbonamento text;
   insert into clients(id,nome,package_types,sessions_total,sessions_remaining,pt_assegnato,package_start) values('a','A',array['PT 1:2'],8,8,'pt','2026-10-01'),('b','B',array['PT 1:2'],12,12,'pt','2026-10-02');
   insert into operators(id,nome,email,roles) values('owner','Owner','owner@example.test',array['owner']),('pt','Trainer','pt@example.test',array['PT']);
   create view operator_effective_roles as select id operator_id,nome,cognome,email,active,roles legacy_roles,'[]'::jsonb system_roles from operators;
   grant select on operator_effective_roles to service_role;
   insert into operator_availability values('pt','mon','["08:00-20:00"]',now());`);
  const ledger=(id,start)=>'[NEACEA-PACKAGE-LEDGER-V1]'+JSON.stringify({cycles:[{id,startDate:start,legacy:false,sessionsTotal:8}]})+'[/NEACEA-PACKAGE-LEDGER-V1]';
  for(const id of ['a','b'])await db.query('update clients set notes=$2 where id=$1',[id,ledger('old-'+id,'2026-10-0'+(id==='a'?1:2))]);
  if(json)await db.exec('alter table appointments alter column client_ids type jsonb using to_jsonb(client_ids); alter table clients alter column package_types type jsonb using to_jsonb(package_types)');
  for(const f of ['20260912151523_calendar_prerelease_atomic.sql','20260912212042_calendar_activity_audit.sql','20260913211931_calendar_flex_mode.sql','20260921101845_calendar_early_package_session.sql'])await db.exec(sql(f));
  if(process.env.PAIR_PRODUCTION_FUNCTIONS)for(const row of JSON.parse(fs.readFileSync(process.env.PAIR_PRODUCTION_FUNCTIONS,'utf8')))await db.exec(row.definition);
  const oids=async()=> (await db.query("select proname,oid from pg_proc where proname in ('calendar_save_appointment','calendar_uses_current_session','calendar_audit_fields') order by proname")).rows;
  const beforeOids=await oids();await db.exec(sql('20261009070726_calendar_pt_pair_rules.sql'));assert.deepEqual(await oids(),beforeOids);

  const query=async(q,v=[])=>{await db.exec('set role service_role');try{return await db.query(q,v)}finally{await db.exec('reset role')}};
  const write=async(a,before,role='owner')=>(await query('select calendar_audit_write($1,$2,$3,$4,$5,$6) r',[role,role==='pt'?'pt':'owner','calendar',crypto.randomUUID(),'save',JSON.stringify({appointment:a,...(before?{expected:before}:{})})])).rows[0].r;
  const balances=async()=> (await db.query('select sessions_remaining n from clients order by id')).rows.map(r=>r.n);
  const appointment={id:'one',service_id:'pt12',client_ids:['a','b'],operator_id:'pt',date:'2026-10-12',start_time:'17:00',duration_min:60,buffer_min:10,status:'prenotato',notes:''};
  await assert.rejects(write({...appointment,client_ids:['a']}),/due clienti/);
  let saved=(await write(appointment)).appointment;
  assert.equal(model.cycle(saved,'a').cycleId,'old-a');assert.equal(model.cycle(saved,'b').cycleId,'old-b');
  assert.deepEqual(await balances(),[8,12]);
  await assert.rejects(write({...appointment,id:'overlap',start_time:'17:30'}),/già impegnato/);
  const mixed=model.attendance(saved,{a:'fatto',b:'noshow'});
  saved=(await write(mixed,saved,'pt')).appointment;assert.deepEqual(await balances(),[7,11]);
  await write(saved,saved,'pt');assert.deepEqual(await balances(),[7,11]);
  let both=model.attendance(saved,{a:'noshow',b:'noshow'});
  saved=(await write(both,saved,'pt')).appointment;assert.deepEqual(await balances(),[7,11]);
  assert.equal(model.summary([saved],'2026-10').totals[0].cents,1500);
  await assert.rejects(write({...saved,service_id:'pt11'},saved,'pt'),/Direzione/);
  const cancelled=(await write({...saved,status:'annullato'},saved)).appointment;assert.deepEqual(await balances(),[8,12]);
  saved=(await write(model.attendance(cancelled,{a:'prenotato',b:'prenotato'}),cancelled)).appointment;assert.deepEqual(await balances(),[8,12]);
  saved=(await write(model.attendance(saved,{a:'fatto',b:'noshow'}),saved)).appointment;assert.deepEqual(await balances(),[7,11]);
  const row=async id=>(await db.query('select to_jsonb(c) r from clients c where id=$1',[id])).rows[0].r;
  const patch=(c,n)=>({id:c.id,notes:ledger('new-'+c.id,'2026-11-02'),sessions_total:n,sessions_remaining:n,data_conferma:'2026-11-02',package_start:'2026-11-02',tipo_servizio:'PT 1:2'});
  const a=await row('a'),b=await row('b');
  const payload={clients:[a,b].map(c=>({id:c.id,expectedUpdatedAt:c.updated_at,renewal:patch(c,8)})),appointments:[{...appointment,id:'renew-1',date:'2026-11-02'}]};
  const request=crypto.randomUUID();
  const renew=async(p=payload,id=request,actor='owner')=>(await query('select calendar_renew_pt_pair($1,$2,$3) r',[actor,id,JSON.stringify(p)])).rows[0].r;
  await assert.rejects(renew(payload,crypto.randomUUID(),'pt'),/Direzione/);
  await assert.rejects(renew({...payload,appointments:[payload.appointments[0],{...payload.appointments[0],id:'renew-2'}]},crypto.randomUUID()),/già impegnato/);
  assert.deepEqual(await balances(),[7,11]);assert.equal((await row('a')).notes,a.notes);
  assert.equal((await db.query('select count(*)::int n from calendar_pt_pair_receipts')).rows[0].n,0);
  const result=await renew();assert.equal(result.appointments.length,1);assert.deepEqual(await balances(),[8,8]);
  assert.equal(model.cycle(result.appointments[0],'a').cycleId,'new-a');assert.equal(model.cycle(result.appointments[0],'b').cycleId,'new-b');
  assert.deepEqual(await renew(),result,'same request returns stored receipt');assert.deepEqual(await balances(),[8,8]);
  await assert.rejects(renew({...payload,appointments:[]}),/già utilizzato/);
  await assert.rejects(renew(payload,crypto.randomUUID()),/cambiato/);
  let future=result.appointments[0];future=(await write(model.attendance(future,{a:'noshow',b:'noshow'}),future,'pt')).appointment;assert.deepEqual(await balances(),[7,7]);
  // Editing old-cycle attendance cannot consume or refund the new cycle.
  await write({...saved,status:'annullato'},saved);assert.deepEqual(await balances(),[7,7]);
  const a2=await row('a'),b2=await row('b');
  const nextPatch={...patch(a2,8),notes:ledger('third-a','2026-12-07'),data_conferma:'2026-12-07',package_start:'2026-12-07'};
  const oneOnly={clients:[{id:'a',expectedUpdatedAt:a2.updated_at,renewal:nextPatch},{id:'b',expectedUpdatedAt:b2.updated_at,renewal:null}],appointments:[{...appointment,id:'one-renews',date:'2026-12-07'}]};
  const oneResult=await renew(oneOnly,crypto.randomUUID());assert.deepEqual(await balances(),[8,7]);
  assert.equal(model.cycle(oneResult.appointments[0],'a').cycleId,'third-a');assert.equal(model.cycle(oneResult.appointments[0],'b').cycleId,'new-b');
  const third=oneResult.appointments[0];
  const forged=model.write(third,{...model.read(third),participants:{...model.read(third).participants,a:{...model.cycle(third,'a'),cycleId:'wrong'}}});
  await assert.rejects(write(forged,third,'pt'),/collegamento/);
  await write(model.attendance(third,{a:'noshow',b:'fatto'}),third,'pt');assert.deepEqual(await balances(),[7,6]);
  const audit=(await db.query("select after_data from calendar_audit_log where entity_id='one-renews' ")).rows;
  assert.ok(audit.some(r=>r.after_data.pt_participants?.a?.status==='noshow'));
  await db.exec('set role anon');await assert.rejects(db.query('select calendar_renew_pt_pair($1,$2,$3)',['owner',crypto.randomUUID(),JSON.stringify(payload)]),/permission denied/);await db.exec('reset role');
 }finally{await db.close()}
});
