const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto');
const {start,seed}=require('./helpers/calendar-postgres.cjs');
(async()=>{const db=await start(),c=db.client;try{
 await seed(c);await c.query("alter table clients add package_frequency text,add giorni_settimana jsonb,add tipo_servizio text,add tipo_abbonamento text,add stato_abbonamento text,add importo numeric,add stato_pagamento text;insert into operators(id,nome,email,roles) values('owner','SIM','owner@example.test',array['Direzione']),('nutrition','SIM','nutrition@example.test',array['Nutrizionista','Valutazioni']);create view operator_effective_roles as select id operator_id,nome,cognome,email,active,roles legacy_roles,'[]'::jsonb system_roles from operators;grant select on operator_effective_roles to service_role");
 await c.query(fs.readFileSync(path.join(__dirname,'../supabase/migrations/20260912212042_calendar_activity_audit.sql'),'utf8'));
 await c.query(fs.readFileSync(path.join(__dirname,'../supabase/migrations/20260912225335_calendar_audit_assignment_partial_unique.sql'),'utf8'));
 async function write(operation,payload,actor='owner',role='owner'){await c.query('set role service_role');try{return(await c.query('select calendar_audit_write($1,$2,$3,$4,$5,$6) r',[actor,role,'calendar',crypto.randomUUID(),operation,JSON.stringify(payload)])).rows[0].r}finally{await c.query('reset role')}}
 const log=async()=>(await c.query('select * from calendar_audit_log order by id')).rows;
 const fields={package_frequency:'2x',giorni_settimana:['Martedì','Giovedì'],tipo_servizio:'PT',tipo_abbonamento:'8 sedute',stato_abbonamento:'Attivo'};
 for(const [key,value] of Object.entries(fields)){const n=(await log()).length;await write('client',{method:'PATCH',rows:[{id:'test',[key]:value}]});const logs=await log();assert.equal(logs.length,n+1);assert.deepEqual(logs.at(-1).after_data[key],value);assert.equal(logs.at(-1).actor_operator_id,'owner')}
 await write('client',{method:'PATCH',rows:[{id:'test',importo:987.65,stato_pagamento:'Pagato',notes:'[CICLO-PACCHETTO 2026-09-15]\nPRIVATE_CLINICAL_DETAILS'}]});let last=(await log()).at(-1);assert.equal(last.action,'client_details_changed');assert.equal(last.metadata.noop,false);assert.ok(!JSON.stringify(await log()).includes('PRIVATE_CLINICAL_DETAILS'));assert.ok(!JSON.stringify(await log()).includes('987.65'));assert.equal(last.after_data.importo,undefined);
 await write('assignment',{clientId:'test',trainerId:'pt'});last=(await log()).find(x=>x.entity_type==='trainer_client_assignments');assert.equal(last.actor_operator_id,'owner');assert.equal(last.after_data.assigned_by,'owner');assert.deepEqual(last.client_ids,['test']);
 const old=(await c.query('select * from trainer_client_assignments order by id')).rows,n=(await log()).length;await write('assignment',{clientId:'test',trainerId:'pt'});assert.equal((await log()).length,n);assert.deepEqual((await c.query('select * from trainer_client_assignments order by id')).rows,old);
 await write('client',{method:'PATCH',rows:[{id:'test',pt_assegnato:'pt2'}]});assert.equal((await c.query("select trainer_id from trainer_client_assignments where client_id='test' and active")).rows[0].trainer_id,'pt2');assert.equal((await c.query("select pt_assegnato from clients where id='test'")).rows[0].pt_assegnato,'pt2');
 await assert.rejects(write('assignment',{clientId:'test',trainerId:'pt'},'pt','pt'),/Assignment requires/);await assert.rejects(write('client',{method:'PATCH',rows:[{id:'test',active:false}]},'nutrition','pt'),/PT role required/);
 await write('assignment',{clientId:'test',trainerId:null});await write('assignment',{clientId:'test',trainerId:'pt2'});assert.equal((await c.query("select count(*)::int n from trainer_client_assignments where client_id='test' and active")).rows[0].n,1);
 const before=JSON.stringify({assignments:(await c.query('select * from trainer_client_assignments order by id')).rows,client:(await c.query("select * from clients where id='test'")).rows,logs:await log()});
 await c.query("create function reject_assignment_log() returns trigger language plpgsql as $$begin if new.entity_type='trainer_client_assignments' then raise exception 'SIM_AUDIT_FAILURE';end if;return new;end$$;create trigger reject_assignment_log before insert on calendar_audit_log for each row execute function reject_assignment_log()");
 await assert.rejects(write('client',{method:'PATCH',rows:[{id:'test',pt_assegnato:'pt'}]}),/SIM_AUDIT_FAILURE/);assert.equal(JSON.stringify({assignments:(await c.query('select * from trainer_client_assignments order by id')).rows,client:(await c.query("select * from clients where id='test'")).rows,logs:await log()}),before);
 for(const role of ['anon','authenticated']){await c.query('set role '+role);for(const sql of ["insert into trainer_client_assignments(id,trainer_id,client_id) values('hack','pt','test')","update trainer_client_assignments set active=false","delete from trainer_client_assignments","truncate trainer_client_assignments","select calendar_audit_set_assignment('test','pt','owner')"]){await assert.rejects(c.query(sql))}await c.query('reset role')}
 await c.query('set role service_role');await assert.rejects(c.query("update trainer_client_assignments set active=false"),/context required/);await c.query('reset role');
 console.log('PASS production SQL: operational fields, private-value redaction, owner attribution, atomic client/assignment/audit, no-op timestamps, public and non-PT rejection');
}finally{await db.close()}})().catch(e=>{console.error(e);process.exitCode=1});
