const {test}=require('node:test'),assert=require('node:assert/strict');
const {candidates,message,createService,SITE}=require('../netlify/functions/lib/email-package-reminder');
const now=new Date('2026-09-23T06:00:00Z');
function fixture(){const c={id:'c',nome:'Cliente',email:'test@example.com',active:true,sessions_remaining:2,sessions_total:8,data_conferma:'2026-09-01'};const rows=[{id:'a',client_ids:['c'],service_id:'pt11',status:'prenotato',date:'2026-09-23',start_time:'10:00'},{id:'b',client_ids:['c'],service_id:'pt11',status:'prenotato',date:'2026-09-30',start_time:'10:00'}];return {c,rows};}
test('penultimate booking uses saved balance and excludes inconsistent schedules',()=>{let {c,rows}=fixture();assert.equal(candidates([c],rows,now).length,1);for(const patch of [{sessions_remaining:3},{active:false},{email:'bad'},{data_conferma:'2026-09-24'}])assert.equal(candidates([{...c,...patch}],rows,now).length,0);assert.equal(candidates([c],rows.slice(0,1),now).length,1);assert.equal(candidates([c],rows.map(r=>({...r,service_id:'circuit'})),now).length,0);assert.equal(candidates([c],[{...rows[0],date:'2026-09-22'},rows[1]],now).length,0);assert.equal(candidates([c],[{...rows[0],status:'fatto'},rows[1]],now).length,0);});
test('cycle IDs isolate renewals, closed or malformed ledgers do not send',()=>{const {c,rows}=fixture();const ledger=cycles=>'[NEACEA-PACKAGE-LEDGER-V1]'+JSON.stringify({cycles})+'[/NEACEA-PACKAGE-LEDGER-V1]';c.notes=ledger([{id:'new',startDate:'2026-09-01'}]);assert.equal(candidates([c],rows,now).length,0);rows.forEach(r=>r.notes='[CICLO-PACCHETTO-ID new]');const key=candidates([c],rows,now)[0].key;c.notes=ledger([{id:'next',startDate:'2026-09-01'}]);rows.forEach(r=>r.notes='[CICLO-PACCHETTO-ID next]');assert.notEqual(candidates([c],rows,now)[0].key,key);c.notes=ledger([{id:'next',closedAt:'2026-09-23'}]);assert.equal(candidates([c],rows,now).length,0);});
test('approved template uses Gmail, full signature, escaped name and no confirmation button',()=>{const p=message({email:'test@example.com',name:'<script>'},{});assert.equal(p.from,'NEACEA Desk <neacea.desk@gmail.com>');assert.match(p.html,/&lt;script&gt;/);assert.match(p.html,/riservate/);assert.match(p.html,/penultima seduta/);assert.doesNotMatch(p.html,/Ho ricevuto/);});
function memory(){const m=new Map();let n=0;return {get:async k=>m.get(k)?.data,getWithMetadata:async k=>m.get(k),setJSON:async(k,d,o={})=>{const old=m.get(k);if(o.onlyIfNew&&old||o.onlyIfMatch&&old?.etag!==o.onlyIfMatch)return {modified:false};const etag=String(++n);m.set(k,{data:structuredClone(d),etag});return {modified:true,etag};},m};}
test('cloud probe sends nothing; concurrent runs and repeated days never duplicate a cycle',async()=>{const {c,rows}=fixture(),store=memory();let calls=0;const s=createService({db:async t=>t==='clients'?[c]:rows,store,env:{EMAIL_PACKAGE_REMINDER_ENABLED:'true',SITE_ID:SITE,CONTEXT:'production',GMAIL_REMINDER_WEBAPP_URL:'https://script.google.com/macros/s/test/exec',GMAIL_REMINDER_SECRET:'test'},now:()=>now,fetchImpl:async()=>{calls++;return {ok:true,json:async()=>({status:'accepted',sender:'neacea.desk@gmail.com',id:'m'})};}});await s.run('d');assert.equal(calls,0);await Promise.all([s.run('d'),s.run('d')]);await s.run('d');assert.equal(calls,1);});
