const {test}=require('node:test'), assert=require('node:assert/strict');
const {createService}=require('../netlify/functions/lib/email-agenda');
function fixture({date='2026-09-18T04:30:00Z',env={},outcome='ok'}={}){
 const data={operators:[{id:'a',nome:'Anna',cognome:'PT',active:true,roles:['PT'],email:'anna@example.test'},{id:'b',nome:'Bruno',active:true,roles:['PT'],email:'bruno@example.test'},{id:'off',active:false,roles:['PT'],email:'off@example.test'}],operator_effective_roles:[],clients:[{id:'c',nome:'Cliente <script>',cognome:'Test',sessions_total:8,sessions_remaining:6}],appointments:[{id:'s1',date:'2026-09-18',start_time:'09:00:00',service_id:'pt11',client_ids:['c'],operator_id:'a',status:'prenotato'}]};
 const ledger=new Map(),calls=[]; let instant=new Date(date);
 const db=async(table,{body}={})=>{if(!table.startsWith('rpc/'))return data[table];const k=body.p_day+'/'+body.p_operator_id;if(table.endsWith('claim')){let row=ledger.get(k);if(row&&(row.status!=='pending'||row.locked))return null;if(!row){row={payload:structuredClone(body.p_payload),status:'pending'};ledger.set(k,row);}row.locked=true;return row.payload;}Object.assign(ledger.get(k),{status:body.p_status,locked:false});return true;};
 const service=createService({db,env:{EMAIL_AGENDA_ENABLED:'true',EMAIL_AGENDA_SITE_ID:'site',SITE_ID:'site',EMAIL_AGENDA_FROM:'NEACEA Desk <desk@neacea.com>',RESEND_API_KEY:'test',...env},now:()=>instant,pause:async()=>{},fetchImpl:async(url,options)=>{calls.push({url,...options});if(outcome==='timeout'&&calls.length===1)throw Error('timeout');return {ok:true,status:200,json:async()=>({id:'test-email'})};}});
 return {service,data,ledger,calls,setDate:d=>instant=new Date(d)};
}
test('Preview contains personal agenda, actual counters and official signature; no send/write',async()=>{const f=fixture();const p=await f.service.run();assert.equal(p.agendas.length,1);assert.deepEqual(p.agendas[0].message.to,['anna@example.test']);assert.match(p.agendas[0].message.html,/Cliente &lt;script&gt;/);assert.match(p.agendas[0].message.html,/NEACEA Desk/);assert.match(p.agendas[0].message.html,/logo-neacea-black/);assert.match(p.agendas[0].message.text,/2\/8/);assert.equal(f.calls.length,0);assert.equal(f.ledger.size,0);});
test('Only assigned active PT gets booked personal sessions, with 1:2 together',async()=>{const f=fixture();for(const status of ['fatto','noshow','annullato'])f.data.appointments.push({...f.data.appointments[0],id:status,status});f.data.appointments.push({...f.data.appointments[0],id:'circuit',service_id:'circuit'},{...f.data.appointments[0],id:'off',operator_id:'off'});const p=await f.service.preview();assert.equal(p.length,1);assert.equal(p[0].count,1);await f.service.run({dryRun:false});assert.equal(f.calls.length,1);assert.deepEqual(JSON.parse(f.calls[0].body).to,['anna@example.test']);});
test('Concurrent and repeated execution cannot resend an accepted agenda',async()=>{const f=fixture();await Promise.all([f.service.run({dryRun:false}),f.service.run({dryRun:false})]);await f.service.run({dryRun:false});assert.equal(f.calls.length,1);});
test('Unknown outcome retries identical payload and key even if live times change',async()=>{const f=fixture({outcome:'timeout'});await f.service.run({dryRun:false});f.data.appointments[0].start_time='10:00:00';f.setDate('2026-09-18T04:35:00Z');await f.service.run({dryRun:false});assert.equal(f.calls.length,2);assert.equal(f.calls[0].body,f.calls[1].body);assert.equal(f.calls[0].headers['Idempotency-Key'],f.calls[1].headers['Idempotency-Key']);});
test('Disable/site/time guards and missing email prevent sending',async()=>{for(const config of [{env:{EMAIL_AGENDA_ENABLED:'false'}},{env:{SITE_ID:'other'}},{date:'2026-09-18T03:30:00Z'},{date:'2026-09-18T05:05:00Z'}]){const f=fixture(config);await f.service.run({dryRun:false});assert.equal(f.calls.length,0);}const f=fixture();f.data.operators[0].email='';await f.service.run({dryRun:false});assert.equal(f.calls.length,0);});
test('Winter and DST dates select the same local morning window',async()=>{for(const date of ['2026-01-14T05:30:00Z','2026-03-29T04:30:00Z','2026-10-25T05:30:00Z']){const f=fixture({date});f.data.appointments[0].date=date.slice(0,10);await f.service.run({dryRun:false});assert.equal(f.calls.length,1);}});
