const {test}=require('node:test'),assert=require('node:assert/strict');
const {createService,buildSummary,windowFor,SITE}=require('../netlify/functions/lib/email-calendar-summary');
function fixture(date='2026-09-20T18:00:00Z'){
 let instant=new Date(date),version=0,fail=false;const blobs=new Map(),calls=[];
 const data={clients:[{id:'c',nome:'=Cliente <script>',cognome:'Test'}],operators:[{id:'p',nome:'PT',cognome:'Test',active:false}],appointments:[]};
 const row=(id,date='2026-09-21',time='10:00:00',status='prenotato',service='pt11')=>({id,date,start_time:time,status,service_id:service,client_ids:['c'],operator_id:'p',duration_min:60});
 data.appointments.push(row('a'));
 const store={getWithMetadata:async k=>structuredClone(blobs.get(k)||null),setJSON:async(k,data,opts={})=>{const old=blobs.get(k);if((opts.onlyIfNew&&old)||(opts.onlyIfMatch&&old?.etag!==opts.onlyIfMatch))return {modified:false};const etag=String(++version);blobs.set(k,{data:structuredClone(data),etag});return {modified:true,etag};},list:async()=>({blobs:[...blobs.keys()].map(key=>({key}))})};
 const env={SITE_ID:SITE,CONTEXT:'production',EMAIL_CALENDAR_SUMMARY_ENABLED:'true',RESEND_API_KEY:'test',EMAIL_AGENDA_FROM:'NEACEA Desk <desk@neacea.com>'};
 const queries=[];const db=async(table,options)=>{assert.equal(options.method,undefined,'Read-only database');queries.push([table,options.query]);const q=new URLSearchParams(options.query.slice(1)),offset=+q.get('offset');return data[table].slice(offset,offset+1000);};
 const service=createService({db,store,env,now:()=>instant,fetchImpl:async(url,options)=>{calls.push(options);if(fail){fail=false;throw Error('timeout');}return {ok:true,status:200,json:async()=>({id:'email-id'})};}});
 return {data,store,blobs,calls,service,env,row,queries,date:d=>instant=new Date(d),fail:()=>fail=true};
}
test('exact next 30 local days include all services, statuses and inactive operators; no private notes',async()=>{
 const f=fixture();f.data.appointments=[f.row('before','2026-09-20','19:59:00'),f.row('start','2026-09-20','20:00:00'),f.row('end','2026-10-20','20:00:00'),f.row('last','2026-10-20','19:59:00')];
 for(const [i,status] of ['prenotato','fatto','noshow','annullato'].entries())f.data.appointments.push({...f.row('s'+i,'2026-09-25','10:00:00',status,'circuit'),notes:'DO NOT INCLUDE'});
 const r=await f.service.preview();assert.equal(r.count,6);assert.deepEqual(r.message.to,['neacea.desk@gmail.com']);assert.match(r.message.html,/&lt;script&gt;/);assert.match(r.message.text,/No-show/);assert.match(r.message.text,/Annullato/);assert.match(r.message.text,/Circuit/);assert.match(r.message.text,/PT Test/);assert.doesNotMatch(r.message.text,/DO NOT INCLUDE/);assert.match(r.message.html,/logo-neacea-black/);assert.equal(f.calls.length,0);assert.equal(f.blobs.size,0);
 const csv=Buffer.from(r.message.attachments[0].content,'base64').toString();assert.match(csv,/'=Cliente/);assert.doesNotMatch(csv,/"before"|"end"/);assert.match(csv,/"last"/);
});
test('pagination over 1000 rows is complete; no truncation in email or attachment',async()=>{const f=fixture();f.data.appointments=Array.from({length:1003},(_,i)=>f.row(String(i)));const p=await f.service.preview();assert.equal(p.count,1003);assert.equal(Buffer.from(p.message.attachments[0].content,'base64').toString().split('\r\n').length,1004);assert.ok(f.queries.some(([,q])=>q.includes('offset=1000')));});
test('concurrent and repeated invocation send once, stable snapshot on retry, no DB writes',async()=>{const f=fixture();f.fail();await Promise.all([f.service.run(),f.service.run()]);assert.equal(f.calls.length,1);f.data.appointments[0].start_time='11:00';f.date('2026-09-20T18:05:00Z');await f.service.run();assert.equal(f.calls.length,2);assert.equal(f.calls[0].body,f.calls[1].body);assert.equal(f.calls[0].headers['Idempotency-Key'],f.calls[1].headers['Idempotency-Key']);await f.service.run();assert.equal(f.calls.length,2);assert.equal(f.blobs.get('delivery/2026-09-20').data.payload,undefined);});
test('weekly snapshot gets a new key and data; zero appointments still produce a trace',async()=>{const f=fixture();await f.service.run();f.date('2026-09-27T18:00:00Z');f.data.appointments=[];const r=await f.service.run();assert.equal(r.count,0);assert.equal(f.calls.length,2);assert.notEqual(f.calls[0].headers['Idempotency-Key'],f.calls[1].headers['Idempotency-Key']);assert.match(JSON.parse(f.calls[1].body).html,/Nessun appuntamento/);});
test('Sunday 20:00 Rome remains correct over DST and month/year boundaries',async()=>{for(const date of ['2026-09-20T18:00:00Z','2026-10-25T19:00:00Z','2026-03-29T18:00:00Z','2026-12-27T19:00:00Z']){const f=fixture(date);await f.service.run();assert.equal(f.calls.length,1);}assert.equal(windowFor(new Date('2026-10-18T18:00:00Z')).end,'2026-11-17T20:00');assert.equal(windowFor(new Date('2026-12-27T19:00:00Z')).end,'2027-01-26T20:00');});
test('disabled, wrong site, preview deploy, weekday and outside window never send',async()=>{for(const [key,val] of [['EMAIL_CALENDAR_SUMMARY_ENABLED','false'],['SITE_ID','other'],['CONTEXT','deploy-preview']]){const f=fixture();f.env[key]=val;await f.service.run();assert.equal(f.calls.length,0);}for(const d of ['2026-09-19T18:00:00Z','2026-09-20T17:59:00Z','2026-09-20T19:00:00Z']){const f=fixture(d);await f.service.run();assert.equal(f.calls.length,0);}});
test('failed snapshot read cannot send a partial digest',async()=>{const f=fixture();const service=createService({env:f.env,store:f.store,now:()=>new Date('2026-09-20T18:00:00Z'),db:async()=>{throw Error('unavailable')},fetchImpl:()=>assert.fail('must not send')});await assert.rejects(service.run(),/unavailable/);assert.equal(f.blobs.size,0);});
