const {test}=require('node:test');const assert=require('node:assert/strict');
const model=require('../netlify/functions/lib/supplements');const sources=require('../netlify/functions/lib/supplement-sources');const {matchRows}=require('../netlify/functions/lib/supplement-import');
test('catalog DTO excludes prices, private identifiers, stock quantities and unknown nested fields',()=>{
 const p={id:'p',name:'C',brand:'B',description:'Text',content:{what:'Creatina',purchase_cost:20},image_url:'https://example.com/p.png',status:'published',updated_by:'secret'};
 const result=model.publicProduct(p,[{id:'v',product_id:'p',active:true,label:'Neutro',format:'300g',sku:'secret',public_price:40,content:{ingredients:'Creatina',margin:12}}],[],[],[{variant_id:'v',stock:6,inventory_value:120}],[{product_id:'p',source_url:'https://example.com',source_name:'Official',verified_at:'2026-09-28',extracted:{price:20}}]);
 const json=JSON.stringify(result);for(const key of ['purchase_cost','public_price','inventory_value','margin','updated_by','secret','extracted','sku'])assert.ok(!json.includes(key),key);assert.equal(result.variants[0].available,true);
});
test('product validation rejects unsafe URLs and requires variants',()=>{assert.throws(()=>model.validateProduct({name:'x',variants:[]}),/VARIANTS_REQUIRED/);assert.throws(()=>model.validateProduct({name:'x',variants:[{label:'x'}],image_url:'javascript:alert(1)'}),/URL_HTTPS_REQUIRED/);});
test('source acquisition refuses local IPs, credentials and arbitrary redirects',()=>{for(const url of ['https://127.0.0.1/test','http://www.powerbar.eu','https://www.powerbar.eu.evil.com','https://a:b@www.powerbar.eu','https://www.powerbar.eu:444/'])assert.throws(()=>sources.validateSource(url));assert.equal(sources.validateSource('https://www.powerbar.eu/en/test').hostname,'www.powerbar.eu');});
test('source parsing never imports prices and leaves uncertain fields pending',()=>{const p=sources.extractProduct('<script type="application/ld+json">{"@type":"Product","name":"C","brand":{"name":"B"},"image":"/p.png","description":"<b>Text</b>","offers":{"price":40}}</script>','https://www.powerbar.eu/item');assert.equal(p.name,'C');assert.equal(p.description,'Text');assert.equal(p.needs_review,true);assert.equal(p.image_url,'https://www.powerbar.eu/p.png');assert.ok(!JSON.stringify(p.content).includes('price'));assert.equal(sources.extractProduct('<p>No metadata</p>','https://www.powerbar.eu').needs_review,true);});
test('document matching never auto-matches ambiguous codes or names only',()=>{const vs=[{id:'a',sku:'sku1',ean:'ean1',label:'A',format:'300g'},{id:'b',sku:'sku2',ean:'ean2',label:'A',format:'300g'}];assert.equal(matchRows([{sku:'sku1'}],vs)[0].variant_id,'a');assert.equal(matchRows([{sku:'sku1',ean:'ean2'}],vs)[0].variant_id,null);assert.equal(matchRows([{label:'A',format:'300g'}],vs)[0].variant_id,null);});
test('economic totals are withheld when tax bases differ',()=>{const i=[{variant_id:'a',stock:1,inventory_value:20,revenue:32,gross_profit:12},{variant_id:'b',stock:1,inventory_value:20,revenue:32,gross_profit:12}];assert.equal(model.kpis([],i,[{variant_id:'a',tax_basis:'gross'},{variant_id:'b',tax_basis:'net'}]).profit,null);assert.equal(model.kpis([],i,[{variant_id:'a',tax_basis:'gross'},{variant_id:'b',tax_basis:'gross'}]).profit,24);});

test('structured enrichment validates sources, dates, fields and zero-cost samples',()=>{
 const workflow=require('../netlify/functions/lib/supplement-workflow');const id=crypto.randomUUID();
 assert.throws(()=>workflow.validate('intake',{request_id:id,brand:'Test',name:'Omega',format:'60',kind:'SAMPLE',quantity:1,unit_cost:5,tax_basis:'gross'}),/SAMPLE_COST_ZERO/);
 const data={request_id:id,variant_id:id,updated_at:'2026-09-30',what_it_does:'Effetti specifici',official_image:'https://example.org/image.png',sources:[{url:'https://example.org/product'}],verification_date:'2026-09-30',public_price:24.9,tags:[{family:'Tipologia',label:'Omega-3'}]};
 assert.equal(workflow.validate('enrich',data).content.effects,'Effetti specifici');assert.throws(()=>workflow.validate('enrich',{...data,sources:[]}),/VERIFICATION_REQUIRED/);assert.throws(()=>workflow.validate('enrich',{...data,official_image:'javascript:alert(1)'}),/URL_HTTPS_REQUIRED/);
 const files=require('../netlify/functions/lib/supplement-files');assert.throws(()=>files.validate({reference:'DDT',base64:Buffer.from('<html>unsafe</html>').toString('base64')}),/INVALID_FILE/);
 const file=files.validate({reference:'DDT',filename:'test.pdf',base64:Buffer.from('%PDF-1.7\nfixture').toString('base64')});assert.equal(file.mime_type,'application/pdf');assert.equal(file.sha256.length,64);
});
