import {test} from 'node:test';import assert from 'node:assert/strict';import crypto from 'node:crypto';import handler from '../netlify/functions/supplements.mjs';
process.env.PT_ACCESS_SECRET='fixture-secret-only';process.env.SUPABASE_SECRET_KEY='fixture-db-key';
function token(role){const payload=Buffer.from(JSON.stringify({operatorId:role,email:role+'@test.local',accessLevel:role,accessVersion:0,exp:Date.now()+60000})).toString('base64url');return payload+'.'+crypto.createHmac('sha256',process.env.PT_ACCESS_SECRET).update(payload).digest('base64url');}
const request=(role,action,data)=>new Request('http://localhost/.netlify/functions/supplements',{method:'POST',headers:{Authorization:'Bearer '+token(role),'Content-Type':'application/json'},body:JSON.stringify({action,data})});
test('API denies every administrative action to PT before querying private data; catalog projection safe',async()=>{const original=global.fetch;const calls=[];global.fetch=async u=>{u=new URL(u);calls.push(u.pathname);let result=[];const table=u.pathname.split('/').at(-1);if(table==='operator_effective_roles')result=[{operator_id:'pt',email:'pt@test.local',active:true,system_roles:['pt'],legacy_roles:[]}];if(table==='operators')result=[{id:'pt',active:true,portal_access_enabled:true,portal_access_version:0}];if(table==='supplement_products')result=[{id:'p',name:'C',brand:'B',content:{what:'X',cost:99},image_url:'https://example.com/p.png'}];if(table==='supplement_variants')result=[{id:'v',product_id:'p',label:'N',active:true}];if(table==='supplement_inventory')result=[{variant_id:'v',stock:10,average_cost:99,revenue:1000}];return new Response(JSON.stringify(result),{status:200});};try{
for(const action of ['upload_document','document_file','intake','enrich','publish','inventory','product','tag','movement','document','import_document','acquire','match_document']){calls.length=0;const r=await handler(request('pt',action,{}));assert.equal(r.status,403,action);assert.ok(calls.every(p=>!p.includes('supplement')),action);}
const r=await handler(request('pt','catalog'));assert.equal(r.status,200);const text=await r.text();for(const key of ['average_cost','revenue','cost','stock'])assert.ok(!text.includes(key),key);assert.ok(text.includes('available'));
}finally{global.fetch=original;}});
test('invalid signature and revoked version are rejected',async()=>{const original=global.fetch;global.fetch=async u=>{const table=new URL(u).pathname.split('/').at(-1);return new Response(JSON.stringify(table==='operators'?[{id:'owner',active:true,portal_access_enabled:true,portal_access_version:1}]:[{operator_id:'owner',email:'owner@test.local',active:true,system_roles:['owner'],legacy_roles:[]}]))};try{assert.equal((await handler(new Request('http://localhost',{method:'POST',body:'{"action":"catalog"}',headers:{Authorization:'Bearer bad.token'}}))).status,403);assert.equal((await handler(request('owner','inventory'))).status,403);}finally{global.fetch=original;}});
test('Direction sees draft catalog entries, PT sees only published products, archived excluded',async()=>{
const original=global.fetch;let activeRole='owner';const products=[{id:'draft',status:'draft',name:'Bozza',content:{cost:99}},{id:'published',status:'published',name:'Pronto'},{id:'archived',status:'archived',name:'Archivio'}];
global.fetch=async address=>{const u=new URL(address),table=u.pathname.split('/').at(-1);let rows=[];
if(table==='operator_effective_roles')rows=[{operator_id:activeRole,email:activeRole+'@test.local',active:true,system_roles:[activeRole],legacy_roles:[]}];
if(table==='operators')rows=[{id:activeRole,active:true,portal_access_enabled:true,portal_access_version:0}];
if(table==='supplement_products'){const filter=u.searchParams.get('status');rows=products.filter(p=>filter==='neq.archived'?p.status!=='archived':filter==='eq.published'?p.status==='published':true);}
return new Response(JSON.stringify(rows));};
try{const owner=await(await handler(request('owner','catalog'))).json();assert.deepEqual(owner.products.map(p=>p.id),['draft','published']);assert.equal(owner.products[0].status,'draft');assert.ok(!JSON.stringify(owner).includes('cost'));
activeRole='pt';const pt=await(await handler(request('pt','catalog'))).json();assert.deepEqual(pt.products.map(p=>p.id),['published']);assert.ok(!('status' in pt.products[0]));}finally{global.fetch=original;}
});
test('inventory returns operator names only through the owner-only branch',async()=>{
 const original=global.fetch;const queries=[];global.fetch=async address=>{const u=new URL(address);queries.push(u);const table=u.pathname.split('/').at(-1);let rows=[];
 if(table==='operator_effective_roles')rows=[{operator_id:'owner',email:'owner@test.local',active:true,system_roles:['owner']}];
 if(table==='operators')rows=u.searchParams.get('select')==='id,nome,cognome'?[{id:'owner',nome:'Direzione',cognome:'Demo'}]:[{id:'owner',active:true,portal_access_enabled:true,portal_access_version:0}];
 return new Response(JSON.stringify(rows));};try{const response=await handler(request('owner','inventory'));assert.equal(response.status,200);const result=await response.json();assert.deepEqual(result.operators,[{id:'owner',nome:'Direzione',cognome:'Demo'}]);assert.ok(queries.some(u=>u.searchParams.get('select')==='id,nome,cognome'));}finally{global.fetch=original;}
});
