(() => {
'use strict';
const $=id=>document.getElementById(id);
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const euro=v=>v===null||v===undefined||v===''?'Da verificare':new Intl.NumberFormat('it-IT',{style:'currency',currency:'EUR'}).format(Number(v));
const pricing=window.supplementPricing;
const saleEuro=v=>v==null?'Da verificare':new Intl.NumberFormat('it-IT',{style:'currency',currency:'EUR',minimumFractionDigits:Number.isInteger(Number(v))?0:2,maximumFractionDigits:2}).format(Number(v));
const sections={what:"Cos’è",effects:'Cosa fa',usefulness:'Perché può essere utile',audience:'Per chi può essere interessante',usage:'Come si utilizza',ingredients:'Ingredienti',nutrition:'Cosa contiene',allergens:'Allergeni',features:'Caratteristiche',warnings:'Da sapere'};
const labels={PURCHASE:'Acquisto',SAMPLE:'Campione',SALE:'Vendita',ADJUSTMENT:'Rettifica',RETURN:'Reso',DAMAGE:'Danneggiato',OTHER:'Altro'};
const sessionKey='neacea-supplements-session';
let token=new URLSearchParams(location.hash.slice(1)).get('access')||sessionStorage.getItem(sessionKey)||'';
if(location.hash)history.replaceState(null,'',location.pathname+location.search);
let pdfManifest=[];
const pdfReady=fetch('pdf-manifest.json').then(r=>r.ok?r.json():[]).then(rows=>{pdfManifest=rows;}).catch(()=>{});
function stable(value){return value&&typeof value==='object'&&!Array.isArray(value)?Object.fromEntries(Object.keys(value).sort().map(k=>[k,stable(value[k])])):value;}
async function updatePdfLink(p,v){
 const link=$('download-sheet');link.hidden=true;link.removeAttribute('href');await pdfReady;
 const row=pdfManifest.find(x=>x.product_id===p.id&&x.variant_id===v.id);if(!row||!/^[a-z0-9-]+\.pdf$/.test(row.file))return;
 const payload={name:p.name||'',brand:p.brand||'',description:p.description||'',image_url:p.image_url||'',label:v.label,format:v.format,variant_image:v.image_url||'',content:{...p.content,...v.content}};
 const hash=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(JSON.stringify(stable(payload))));
 const signature=[...new Uint8Array(hash)].map(b=>b.toString(16).padStart(2,'0')).join('');
 if(signature!==row.signature||currentProduct?.id!==p.id||$('sheet-variant').value!==v.id)return;
 $('sheet-photo-note').textContent=row.image_note||'';link.href='pdf/'+row.file;link.hidden=false;link.textContent=row.review_required?'PDF · verifica etichetta':'Apri PDF A4';
}
let catalogue={products:[],tags:[]},warehouse=null,role='',view='catalog',selectedTags=new Set(),currentProduct=null,editorSave=null,editingProduct=null;
const image=(url,alt,cls='',scale=1)=>{if(!url)return '';try{const u=new URL(url,location.href);if(!['https:','http:'].includes(u.protocol))return '';return `<img class="${esc(cls)}" style="transform:scale(${Math.min(3,Math.max(1,Number(scale)||1))})" src="${esc(u.href)}" alt="${esc(alt)}" loading="lazy" referrerpolicy="no-referrer">`;}catch{return '';}};
const chips=tags=>(tags||[]).map(t=>`<span class="chip" style="--tag:${/^#[0-9a-f]{6}$/i.test(t.color)?t.color:'#033d27'}">${esc(t.label)}</span>`).join('');
function status(text){$('status').textContent=text;}
async function api(action,data={}){const r=await fetch('/.netlify/functions/supplements',{method:'POST',headers:{'Content-Type':'application/json',Authorization:'Bearer '+token},body:JSON.stringify({action,...data})});const result=await r.json();if(!r.ok){if(r.status===403){warehouseView.clear();warehouse=null;role='';$('inventory-nav').hidden=true;['inventory','catalog','sheet-view'].forEach(id=>$(id).hidden=true);$('login').hidden=false;sessionStorage.removeItem(sessionKey);}throw Error(result.error||'Operazione non disponibile');}return result;}
function show(next){view=next;['catalog','inventory','sheet-view'].forEach(id=>$(id).hidden=id!==next);$('catalog-nav').classList.toggle('active',next!=='inventory');$('inventory-nav').classList.toggle('active',next==='inventory');}
async function loadCatalog(){status('Caricamento del catalogo…');catalogue=await api('catalog');role=catalogue.role;if(role!=='owner'){warehouse=null;warehouseView.clear();}$('inventory-nav').hidden=role!=='owner';$('login').hidden=true;sessionStorage.setItem(sessionKey,token);renderFilters();renderCards();show('catalog');status('');}
function renderFilters(){const families=[...new Set(catalogue.tags.map(t=>t.family))];$('filters').innerHTML=families.map(f=>`<div class="filter-family"><span>${esc(f)}</span>${catalogue.tags.filter(t=>t.family===f).map(t=>`<button class="chip" data-tag="${esc(t.id)}" aria-pressed="${selectedTags.has(t.id)}" style="--tag:${/^#[0-9a-f]{6}$/i.test(t.color)?t.color:'#033d27'}">${esc(t.label)}</button>`).join('')}</div>`).join('')+(selectedTags.size?'<button id="reset-tags">Azzera filtri</button>':'');}
const draftNotice=p=>p.status==='draft'?'<p class="pending">Da completare · visibile solo alla Direzione</p>':'';
function renderCards(){const query=$('search').value.toLocaleLowerCase('it');const products=catalogue.products.filter(p=>[p.name,p.brand,...p.variants.map(v=>v.label+' '+v.format)].join(' ').toLocaleLowerCase('it').includes(query)&&[...selectedTags].every(id=>p.tags.some(t=>t.id===id)));$('count').textContent=products.length+(products.length===1?' prodotto':' prodotti');$('cards').innerHTML=products.length?products.map(p=>`<article class="product-card"><div class="product-visual">${image(p.image_url,p.name,'',p.image_scale)||'<span class="muted">Foto da aggiungere</span>'}</div><div class="product-copy"><span class="eyebrow">${esc(p.brand)}</span><h2>${esc(p.name)}</h2>${draftNotice(p)}<p>${esc(p.variants.map(v=>v.format+' · '+v.label).join(' / '))}</p><div class="chips">${chips(p.tags)}</div><p>${esc(p.description)}</p><span class="availability">${p.variants.some(v=>v.available)?'● Disponibile in studio':'Disponibilità da chiedere in studio'}</span><button data-product="${esc(p.id)}">${p.status==='draft'?'Anteprima scheda':'Scopri il prodotto ↗'}</button>${role==='owner'?` <button data-edit-catalog="${esc(p.id)}">Completa / modifica</button>`:''}</div></article>`).join(''):'<div class="empty"><h2>Nessun prodotto da mostrare</h2><p>Prova a cambiare ricerca o filtri. I nuovi prodotti compaiono dopo la verifica della scheda.</p></div>';}
function openSheet(id){currentProduct=catalogue.products.find(p=>p.id===id);if(!currentProduct)return;$('sheet-variant').innerHTML=currentProduct.variants.map(v=>`<option value="${esc(v.id)}">${esc(v.label)} · ${esc(v.format)}</option>`).join('');renderSheet();show('sheet-view');window.scrollTo(0,0);}
function renderSheet(){const p=currentProduct,v=p.variants.find(v=>v.id===$('sheet-variant').value)||p.variants[0]||{};const content={...p.content,...v.content};updatePdfLink(p,v).catch(()=>{});$('sheet').className='sheet';$('sheet').innerHTML=`<header class="sheet-brand"><img src="assets/neacea-logotipo.svg" alt="NEACEA"><span>NUTRIZIONE & ALLENAMENTO<br>CORPO & ANIMA</span></header><div class="sheet-hero"><div class="sheet-photo">${image(v.image_url||p.image_url,p.name,'',p.image_scale)}<small id="sheet-photo-note"></small></div><div><p class="eyebrow">${esc(p.brand)}</p><h1>${esc(p.name)}</h1>${draftNotice(p)}<p>${esc(v.format)} · ${esc(v.label)}</p><p>${esc(p.description)}</p><div class="chips">${chips(p.tags)}</div></div></div><div class="sheet-sections">${Object.entries(sections).filter(([key])=>content[key]).map(([key,title])=>`<section class="sheet-section"><h2>${esc(title)}</h2><p>${esc(content[key])}</p></section>`).join('')}</div><div class="sheet-sources">${p.sources.length?'Fonti: '+p.sources.map(s=>`<a href="${esc(s.source_url)}" target="_blank" rel="noopener noreferrer">${esc(s.source_name)}</a> · verificato ${new Date(s.verified_at).toLocaleDateString('it-IT')}`).join(' / '):'Dati da verificare sull’etichetta del prodotto.'}</div><footer class="sheet-footer"><span>PERSONE PIÙ CONSAPEVOLI.<br>PIÙ IN FORMA. PIÙ LIBERE.</span><span>IL TUO PERCORSO,<br>LA NOSTRA METODOLOGIA.</span></footer>`;}
let inventoryLoading=null;
async function loadInventory(){if(role!=='owner')throw Error('Accesso riservato alla Direzione');if(inventoryLoading)return inventoryLoading;inventoryLoading=(async()=>{status('Caricamento del magazzino…');const result=await api('inventory');if(role!=='owner'||result.role!=='owner')throw Error('Accesso riservato alla Direzione');warehouse=result;renderInventory();show('inventory');status('Magazzino aggiornato alle '+new Date().toLocaleTimeString('it-IT',{hour:'2-digit',minute:'2-digit',second:'2-digit'}));})();try{await inventoryLoading;}finally{inventoryLoading=null;}}
const warehouseView=window.createSupplementWarehouseView({esc,euro,saleEuro,image,pricing,labels});
function renderInventory(){warehouseView.render(warehouse);}
function field(label,name,value='',type='text',extra=''){return `<label>${esc(label)}<input name="${esc(name)}" type="${type}" value="${esc(value??'')}" ${extra}></label>`;}
function select(label,name,options,value){return `<label>${esc(label)}<select name="${name}">${options.map(([id,title])=>`<option value="${esc(id)}" ${id===value?'selected':''}>${esc(title)}</option>`).join('')}</select></label>`;}
function dialog(title,html,save){$('dialog-title').textContent=title;$('editor-fields').innerHTML=html;$('editor-error').textContent='';$('save-editor').textContent='Salva';editorSave=save;$('editor').showModal();}
function variantEditor(v={}){return `<fieldset class="variant-editor" data-variant="${esc(v.id||'')}"><legend>Variante e prezzi</legend><div class="form-grid">${field('Gusto / variante','label',v.label||'Neutro','text','required')}${field('Formato','format',v.format)}${field('SKU','sku',v.sku)}${field('EAN','ean',v.ean)}${field('Foto specifica variante (URL)','image_url',v.image_url,'url')}${field('Prezzo pubblico (sulla base IVA scelta)','public_price',v.public_price,'number','min="0" step="0.01"')}${field('Prezzo vendita IVA inclusa (vuoto = −20%, arrotondato)','actual_sale_price',pricing.gross(v.actual_sale_price,v),'number','min="0" step="0.5"')}${field('Soglia riordino','reorder_level',v.reorder_level??2,'number','min="0" step="1"')}${select('Base prezzi / costi','tax_basis',[['unknown','Da verificare'],['gross','IVA inclusa'],['net','IVA esclusa']],v.tax_basis||'unknown')}${field('Aliquota IVA % (se nota)','vat_rate',v.vat_rate,'number','min="0" max="100" step="0.01"')}${select('Stato variante','active',[['true','Attiva'],['false','Archiviata']],String(v.active!==false))}</div><details><summary>Contenuti specifici di questo gusto / formato</summary><p class="muted">Questi campi sostituiscono quelli comuni: controlla soprattutto ingredienti, allergeni e dose.</p>${Object.entries(sections).map(([key,label])=>`<label>${label}<textarea data-content="${key}">${esc(v.content?.[key]||'')}</textarea></label>`).join('')}</details></fieldset>`;}
function editProduct(id){const p=warehouse.products.find(p=>p.id===id)||{variants:[{}],content:{},status:'draft'};editingProduct=p;const variants=p.id?warehouse.variants.filter(v=>v.product_id===p.id).map(v=>({...v,...warehouse.prices.find(x=>x.variant_id===v.id)})):[{}];const source=warehouse.sources.filter(s=>s.product_id===p.id).at(-1)||{};
 dialog(p.id?'Modifica scheda':'Nuovo integratore',`<div class="form-grid">${field('Nome','name',p.name,'text','required')}${field('Marca','brand',p.brand)}${field('Fotografia ufficiale (URL)','image_url',p.image_url,'url')}${field('Ingrandimento foto (1–3)','image_scale',p.image_scale||1,'number','min="1" max="3" step="0.1"')}${select('Stato','status',[['draft','Bozza / da verificare'],['published','Pubblicato'],['archived','Archiviato']],p.status)}<label class="wide">Descrizione breve<textarea name="description">${esc(p.description||'')}</textarea></label>${field('Fonte ufficiale (URL)','source_url',source.source_url,'url')}${field('Nome fonte','source_name',source.source_name)}</div><button type="button" id="acquire-product">Recupera dati dalla fonte</button><p class="muted">Il recupero propone dati da verificare. Non pubblica e non trasferisce prezzi dal sito.</p><div id="source-result"></div><div class="check-tags">${warehouse.tags.map(t=>`<label><input type="checkbox" name="tag" value="${t.id}" ${warehouse.links.some(l=>l.product_id===p.id&&l.tag_id===t.id)?'checked':''}>${esc(t.family)} · ${esc(t.label)}</label>`).join('')}</div><div class="form-grid">${Object.entries(sections).map(([key,label])=>`<label>${label}<textarea name="content_${key}">${esc(p.content?.[key]||'')}</textarea></label>`).join('')}</div><div id="variant-editors">${variants.map(variantEditor).join('')}</div><button id="add-variant" type="button">+ Aggiungi variante</button><p><label><input type="checkbox" name="approved">Ho verificato fotografia, dati, varianti, tag e fonte ufficiale. Approva per il catalogo.</label></p>`,async form=>{
 const f=new FormData(form),data={id:p.id,updated_at:p.updated_at,name:f.get('name'),brand:f.get('brand'),image_url:f.get('image_url'),image_scale:Number(f.get('image_scale')),status:f.get('status'),description:f.get('description'),source_url:f.get('source_url'),source_name:f.get('source_name'),approved:f.get('approved')==='on',tags:f.getAll('tag'),content:Object.fromEntries(Object.keys(sections).map(k=>[k,f.get('content_'+k)])),variants:[...form.querySelectorAll('.variant-editor')].map(el=>{const v={id:el.dataset.variant||undefined,content:{}};el.querySelectorAll('input,select').forEach(input=>v[input.name]=input.value===''?null:input.value);el.querySelectorAll('[data-content]').forEach(input=>{if(input.value.trim())v.content[input.dataset.content]=input.value;});v.active=v.active==='true';v.actual_sale_price=pricing.base(v.actual_sale_price,v);return v;})};await api('product',{data});await loadInventory();
 });$('add-variant').onclick=()=>$('variant-editors').insertAdjacentHTML('beforeend',variantEditor());$('acquire-product').onclick=async e=>{e.target.disabled=true;try{const form=$('editor-form');const data=await api('acquire',{url:form.elements.source_url.value});for(const key of ['name','brand','description','image_url','source_name'])if(data[key])form.querySelector('[name="'+key+'"]').value=data[key];for(const [k,v] of Object.entries(data.content||{}))if(form.elements['content_'+k])form.elements['content_'+k].value=v;$('source-result').innerHTML='<p class="pending">Da verificare sull’etichetta della variante prima di pubblicare.</p><details><summary>Testo recuperato dalla fonte</summary><div class="source-excerpt">'+esc(data.source_excerpt||data.message||'')+'</div></details>';}catch(err){$('editor-error').textContent=err.message;}finally{e.target.disabled=false;}};}

function intakeProduct(){const request_id=crypto.randomUUID();dialog('Nuovo prodotto / nuovo carico',`<p class="muted">Inserisci i dati essenziali: se il prodotto esiste viene aggiornato il magazzino; altrimenti viene creata una bozza. La scheda illustrativa si importa successivamente.</p><div class="form-grid">${field('Marca','brand','','text','required')}${field('Nome prodotto','name','','text','required')}${field('Variante','variant','Standard')}${field('Formato','format','','text','required placeholder="es. 60 softgels"')}${field('EAN (facoltativo)','ean')}${field('SKU (facoltativo)','sku')}${field('Confezioni ricevute','quantity',1,'number','min="1" step="1" required')}${select('Approvvigionamento','kind',[['PURCHASE','Acquisto'],['SAMPLE','Campione gratuito']],'PURCHASE')}${field('Costo unitario effettivo','unit_cost','','number','min="0" step="0.0001" required')}${select('Base del costo','tax_basis',[['gross','IVA inclusa'],['net','IVA esclusa']],'gross')}${field('IVA % (se nota)','vat_rate','','number','min="0" max="100" step="0.01"')}${field('Documento / riferimento','document_ref')}${field('Lotto (se noto)','lot')}</div>`,async form=>{await api('intake',{data:{...Object.fromEntries(new FormData(form)),request_id}});await loadInventory();});const form=$('editor-form');form.elements.kind.onchange=()=>{const sample=form.elements.kind.value==='SAMPLE';form.elements.unit_cost.value=sample?'0':'';form.elements.unit_cost.readOnly=sample;};$('save-editor').textContent='Registra carico';}
function enrichProduct(id){const v=warehouse.variants.find(v=>v.id===id),p=warehouse.products.find(p=>p.id===v.product_id),request_id=crypto.randomUUID();dialog('Importa scheda verificata · '+p.name,`<p class="muted">Carica i dati JSON ricevuti dal processo autorizzato: testi, fotografia ufficiale, fonti, data di verifica, tag e prezzo pubblico. Dopo l’importazione controlla l’anteprima nel catalogo e scegli Pubblica.</p><input type="file" id="structured-file" accept="application/json,.json"><label>Dati della scheda<textarea name="structured" rows="14" required placeholder='{"description":"…","what_it_is":"…","what_it_does":"…","suggested_use":"…","official_image":"https://…","public_price":24.90,"sources":[{"url":"https://…","name":"Produttore"}],"verification_date":"2026-09-30","tags":[{"family":"Tipologia","label":"Omega-3"}]}'></textarea></label><p class="muted">Prezzi sulla base IVA già scelta per questa variante. La scheda resta in bozza fino all’approvazione.</p>`,async form=>{const data=JSON.parse(new FormData(form).get('structured'));await api('enrich',{data:{...data,variant_id:id,updated_at:p.updated_at,request_id}});await loadInventory();});$('structured-file').onchange=async e=>{const file=e.target.files[0];if(file&&file.size<=500000)$('editor-form').elements.structured.value=await file.text();};$('save-editor').textContent='Importa in bozza';}
function publishProduct(id){const v=warehouse.variants.find(v=>v.id===id),p=warehouse.products.find(p=>p.id===v.product_id),request_id=crypto.randomUUID();dialog('Pubblica · '+p.name,`<p>Il prodotto sarà visibile ai PT nel catalogo condiviso.</p>${image(p.image_url,p.name,'',1)}<p>${esc(p.description)}</p>${Object.entries(sections).filter(([k])=>p.content?.[k]).map(([k,title])=>`<h3>${esc(title)}</h3><p style="white-space:pre-line">${esc(p.content[k])}</p>`).join('')}<label><input type="checkbox" name="approved" required>Ho controllato la scheda, la fotografia, il prezzo e le fonti ufficiali.</label>`,async()=>{await api('publish',{data:{variant_id:id,updated_at:p.updated_at,request_id,approved:true}});await loadInventory();});$('save-editor').textContent='Pubblica nel catalogo';}

function movement(id,kind='PURCHASE',returnOf=null){const v=warehouse.variants.find(v=>v.id===id),p=warehouse.products.find(p=>p.id===v.product_id),price=warehouse.prices.find(i=>i.variant_id===id)||{},req=crypto.randomUUID();let savedMovement=null;const sale=returnOf?warehouse.movements.find(m=>m.id===returnOf):null;
 dialog(`${labels[kind]} · ${p.name}`,`<p>${esc(v.label)} · ${esc(v.format)}</p><div class="form-grid">${select('Movimento','kind',Object.entries(labels).filter(([key])=>key!=='RETURN'||returnOf),kind)}${field('Quantità (rettifica/altro: usare il segno − per scaricare)','quantity',1,'number','step="1" required')}${field('Costo unitario effettivo di carico','unit_cost','','number','min="0" step="0.0001"')}${field('Prezzo vendita unitario IVA inclusa','sale_price',sale?pricing.gross(sale.sale_price,sale):pricing.sale(price),'number','min="0" step="0.5"')}${field('Riferimento DDT / documento','document_ref')}${field('Lotto','lot')}<label class="wide">Note<textarea name="notes"></textarea></label></div><p class="muted">I campioni hanno costo zero. Per gli acquisti usa il costo effettivo del documento. Prezzo suggerito: pubblico IVA inclusa −20%, arrotondato ai €0,50 più vicini. I prezzi già registrati restano invariati. Base dei costi: ${esc(price.tax_basis==='gross'?'IVA inclusa':price.tax_basis==='net'?'IVA esclusa':'da verificare')}.</p>`,async form=>{const data={...Object.fromEntries(new FormData(form)),variant_id:id,request_id:req,return_of:returnOf};data.sale_price=pricing.base(data.sale_price,price);if(data.kind==='SAMPLE')data.unit_cost=0;if(!savedMovement)savedMovement=(await api('movement',{data})).result;try{await loadInventory();const stock=warehouse.inventory.find(i=>i.variant_id===id)?.stock;status(labels[savedMovement.kind]+' registrata: '+Math.abs(Number(savedMovement.quantity))+' confezione/i di '+p.name+'. Giacenza attuale: '+stock+'.');}catch(err){status('Movimento già registrato. Non reinserirlo: premi Aggiorna magazzino per leggere le quantità. '+err.message);}});$('save-editor').textContent=kind==='SALE'?'Conferma vendita':'Registra movimento';}
function tagsEditor(){dialog('Tag del catalogo',`<p class="muted">I tag sono condivisi da filtri e schede. Modificarli aggiorna tutti i prodotti collegati.</p>${select('Tag','tag_id',[['','Nuovo tag'],...warehouse.tags.map(t=>[t.id,t.family+' · '+t.label])],'')}<div class="form-grid">${field('Famiglia','family','Obiettivo','text','required')}${field('Nome tag','label','','text','required')}${field('Colore','color','#033d27','color')}</div>`,async form=>{const f=new FormData(form);await api('tag',{data:{id:f.get('tag_id')||undefined,family:f.get('family'),label:f.get('label'),color:f.get('color')}});await loadInventory();});$('editor-form').elements.tag_id.onchange=e=>{const t=warehouse.tags.find(t=>t.id===e.target.value);if(t)for(const k of ['family','label','color'])$('editor-form').elements[k].value=t[k];};}
function documentEditor(id){const doc=warehouse.documents.find(d=>d.id===id);if(doc?.rows.length){dialog('Verifica DDT · '+doc.reference,`<p class="pending">Verifica abbinamenti, quantità, tipo e costi. Le righe nuove creano una bozza e registrano il carico in un’unica operazione.</p>${doc.rows.map((r,n)=>`<fieldset class="variant-editor" data-row="${n}"><legend>Riga ${n+1} · ${esc(r.name||r.sku||r.ean||'')}</legend><div class="form-grid">${select('Prodotto','variant_id',[['','Nuovo / identifica dai dati sotto'],...warehouse.variants.map(v=>[v.id,(warehouse.products.find(p=>p.id===v.product_id)?.name||'')+' · '+v.label+' · '+v.format])],r.variant_id||'')}${select('Tipo','kind',[['PURCHASE','Acquisto'],['SAMPLE','Campione']],r.kind||'PURCHASE')}${field('Confezioni','quantity',r.quantity,'number','min="1" step="1" required')}${field('Costo unitario effettivo','unit_cost',r.kind==='SAMPLE'?0:r.unit_cost,'number','min="0" step="0.0001" required')}${field('Marca (nuovo prodotto)','brand',r.brand)}${field('Nome (nuovo prodotto)','name',r.name)}${field('Variante','variant',r.variant||r.label||'Standard')}${field('Formato (nuovo prodotto)','format',r.format)}${field('EAN','ean',r.ean)}${field('SKU','sku',r.sku)}${select('Base costo per nuova variante','tax_basis',[['gross','IVA inclusa'],['net','IVA esclusa']],r.tax_basis||'gross')}${field('IVA % se nota','vat_rate',r.vat_rate,'number','min="0" max="100" step="0.01"')}${field('Lotto','lot',r.lot)}</div></fieldset>`).join('')}`,async form=>{const rows=[...form.querySelectorAll('[data-row]')].map(el=>{const row={...doc.rows[Number(el.dataset.row)]};el.querySelectorAll('input,select').forEach(i=>row[i.name]=i.value);if(row.kind==='SAMPLE')row.unit_cost=0;return {...row,request_id:row.request_id||crypto.randomUUID()};});if(rows.some(r=>!r.variant_id&&(!r.brand||!r.name||!r.format)))throw Error('Per ogni prodotto nuovo indica marca, nome e formato.');await api('document',{data:{...doc,rows}});await api('import_document',{data:{id:doc.id}});await loadInventory();});$('save-editor').textContent='Conferma e registra carico';return;}
 dialog(doc?'Aggiungi righe · '+doc.reference:'Carica foto / DDT / fattura',`${field('Riferimento documento','reference',doc?.reference||'','text','required')}<label>Originale riservato alla Direzione (facoltativo)<input type="file" id="original-document" accept="application/pdf,image/jpeg,image/png,image/webp"></label><p class="muted">PDF o foto fino a 2,5 MB. L’originale viene conservato senza muovere lo stock. L’estrazione non è automatica: un processo autorizzato può leggere il file tramite API e restituire le righe da verificare.</p><label>Righe estratte (JSON, facoltativo)<input type="file" id="document-file" accept="application/json,.json"><textarea name="rows" rows="10" placeholder='[{"brand":"…","name":"…","format":"60 softgels","quantity":1,"kind":"SAMPLE","unit_cost":0,"tax_basis":"gross"}]'></textarea></label>`,async form=>{const f=new FormData(form),file=$('original-document').files[0];let documentId=doc?.id;if(file){if(file.size>2500000)throw Error('Il file supera 2,5 MB.');const base64=await new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(reader.result.split(',')[1]);reader.onerror=reject;reader.readAsDataURL(file);});const saved=await api('upload_document',{data:{reference:f.get('reference'),filename:file.name,base64}});documentId=saved.result.id;}
 const raw=f.get('rows').trim();if(raw){const rows=JSON.parse(raw);if(!Array.isArray(rows)||!rows.length)throw Error('Inserisci un elenco di righe.');const matched=await api('match_document',{rows});await api('document',{data:{id:documentId,reference:f.get('reference'),rows:matched.rows}});}else if(!file)throw Error('Carica il documento oppure le righe estratte.');await loadInventory();});$('document-file').onchange=async e=>{const file=e.target.files[0];if(file){if(file.size>500000){$('editor-error').textContent='File troppo grande';return;}$('editor-form').elements.rows.value=await file.text();}};$('save-editor').textContent='Salva per verifica';}
async function downloadDocument(id){try{const {file}=await api('document_file',{id});const bytes=Uint8Array.from(atob(file.base64),c=>c.charCodeAt(0)),url=URL.createObjectURL(new Blob([bytes],{type:file.mime_type})),a=document.createElement('a');a.href=url;a.download=file.filename||'documento';a.click();setTimeout(()=>URL.revokeObjectURL(url),30000);}catch(e){status(e.message);}}
$('editor-form').onsubmit=async e=>{e.preventDefault();const button=$('save-editor');button.disabled=true;$('editor-error').textContent='';try{await editorSave(e.currentTarget);$('editor').close();}catch(err){$('editor-error').textContent=err.message;}finally{button.disabled=false;}};
$('close-editor').onclick=$('cancel-editor').onclick=()=>$('editor').close();
$('login-form').onsubmit=async e=>{e.preventDefault();const f=new FormData(e.currentTarget);status('Verifica accesso…');try{const r=await fetch('/.netlify/functions/pt-access-email',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'verify',email:f.get('email'),code:f.get('code')})});const data=await r.json();if(!r.ok||!data.token)throw Error(data.error||'Accesso non valido');token=data.token;await loadCatalog();e.target.reset();if(new URLSearchParams(location.search).get('view')==='inventory'&&role==='owner')await loadInventory();}catch(err){status(err.message);}};
$('filters').onclick=e=>{const tag=e.target.closest('[data-tag]');if(tag){selectedTags.has(tag.dataset.tag)?selectedTags.delete(tag.dataset.tag):selectedTags.add(tag.dataset.tag);renderFilters();renderCards();}if(e.target.id==='reset-tags'){selectedTags.clear();renderFilters();renderCards();}};
$('cards').onclick=async e=>{const edit=e.target.closest('[data-edit-catalog]');if(edit){try{await loadInventory();editProduct(edit.dataset.editCatalog);}catch(err){status(err.message);}return;}const target=e.target.closest('[data-product]');if(target)openSheet(target.dataset.product);};
$('search').oninput=renderCards;$('sheet-variant').onchange=renderSheet;
$('back-catalog').onclick=()=>show('catalog');$('print-sheet').onclick=async()=>{await document.fonts.ready;await Promise.all([...$('sheet').images].map(i=>i.decode().catch(()=>{})));window.print();};
$('catalog-nav').onclick=()=>loadCatalog().catch(e=>status(e.message));$('inventory-nav').onclick=()=>loadInventory().catch(e=>status(e.message));$('refresh-inventory').onclick=()=>loadInventory().catch(e=>status(e.message));$('new-product').onclick=intakeProduct;$('manage-tags').onclick=tagsEditor;$('new-document').onclick=()=>documentEditor();
$('inventory').addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.sell)movement(b.dataset.sell,'SALE');if(b.dataset.move)movement(b.dataset.move);if(b.dataset.edit)editProduct(b.dataset.edit);if(b.dataset.enrich)enrichProduct(b.dataset.enrich);if(b.dataset.publish)publishProduct(b.dataset.publish);if(b.dataset.return){const sale=warehouse.movements.find(m=>m.id===b.dataset.return);movement(sale.variant_id,'RETURN',sale.id);}if(b.dataset.document)documentEditor(b.dataset.document);if(b.dataset.original)downloadDocument(b.dataset.original);});
document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='visible'&&view==='inventory'&&role==='owner'&&!$('editor').open)loadInventory().catch(e=>status(e.message));});
(async()=>{if(!token){$('login').hidden=false;status('');return;}try{await loadCatalog();if(new URLSearchParams(location.search).get('view')==='inventory'&&role==='owner')await loadInventory();}catch(e){status(e.message);}})();
})();
