'use strict';
window.createSupplementWarehouseView=function({esc,euro,saleEuro,image,pricing,labels}){
const $=id=>document.getElementById(id),M=window.supplementWarehouse;
const tabs=['overview','products','sales','movements','reorders'];
let data=null,section=new URLSearchParams(location.search).get('tab')||'overview',salePeriod='month',salePage=0,movePage=0;
if(!tabs.includes(section))section='overview';
const basis=b=>b==='net'?'IVA esclusa':b==='gross'?'IVA inclusa':'IVA da verificare';
const percent=n=>n==null?'—':new Intl.NumberFormat('it-IT',{maximumFractionDigits:1}).format(n)+'%';
const date=s=>new Date(s).toLocaleString('it-IT',{timeZone:'Europe/Rome',day:'2-digit',month:'2-digit',year:'numeric',hour:'2-digit',minute:'2-digit'});
const kpi=(label,value,hint='')=>`<div class="kpi"><small>${esc(label)}</small><strong>${esc(value)}</strong>${hint?`<span class="muted">${esc(hint)}</span>`:''}</div>`;
const empty=text=>`<div class="warehouse-empty">${esc(text)}</div>`;
const metric=(t,key)=>!t.count?(key==='margin'?'—':euro(0)):t.groups.map(g=>(key==='margin'?percent(g.margin):euro(g[key]))+' · '+basis(g.basis)).join('\n');
const lookup=id=>{const v=data.variants.find(x=>x.id===id)||{},p=data.products.find(x=>x.id===v.product_id)||{};return {v,p};};
const operator=id=>{const o=(data.operators||[]).find(o=>o.id===id);return o?[o.nome,o.cognome].filter(Boolean).join(' '):id||'Non disponibile';};
const productText=(id,withPhoto=true)=>{const {p,v}=lookup(id);const copy=`<span class="product-identity-copy"><strong>${esc(p.name||'Prodotto non disponibile')}</strong><small>${esc(v.label||'')} · ${esc(v.format||'')}</small></span>`;return withPhoto?`<div class="product-identity"><div class="product-thumbnail">${image(v.image_url||p.image_url,p.name||'Integratore','',p.image_scale)||'<span>Foto non disponibile</span>'}</div>${copy}</div>`:copy;};
const paginate=(rows,page,type)=>rows.length>20?`<div class="pagination"><button data-page="${type}" data-delta="-1" ${page===0?'disabled':''}>← Precedenti</button><span>${page*20+1}–${Math.min(rows.length,(page+1)*20)} di ${rows.length}</span><button data-page="${type}" data-delta="1" ${(page+1)*20>=rows.length?'disabled':''}>Successivi →</button></div>`:'';
function selectTab(next,focus=false){if(!tabs.includes(next))return;section=next;for(const name of tabs){const selected=name===next;$('panel-'+name).hidden=!selected;const button=$('tab-'+name);button.setAttribute('aria-selected',String(selected));button.tabIndex=selected?0:-1;}if(focus)$('tab-'+next).focus();if(data){const u=new URL(location.href);u.searchParams.set('view','inventory');u.searchParams.set('tab',next);history.replaceState(null,'',u.pathname+u.search);}}
function overview(){
 const t=M.totals(M.sales(data.movements,M.period('month'))),low=M.products(data).filter(x=>x.low);
 const values=data.kpis.totals_by_basis||[];const value=data.kpis.value!=null?euro(data.kpis.value)+(data.kpis.tax_basis?' · '+basis(data.kpis.tax_basis):''):values.map(g=>euro(g.value)+' · '+basis(g.tax_basis)).join('\n')||'Da verificare';
 $('overview-period').textContent=new Date().toLocaleDateString('it-IT',{timeZone:'Europe/Rome',month:'long',year:'numeric'});
 $('kpis').innerHTML=kpi('Valore magazzino',value)+kpi('Unità disponibili',data.kpis.units)+kpi('Vendite del mese',t.count,'Movimenti SALE')+kpi('Incasso del mese',euro(t.receipt),'IVA inclusa')+kpi('Costo del venduto',metric(t,'cost'),'Mese corrente')+kpi('Utile lordo',metric(t,'profit'),'Mese corrente')+kpi('Margine medio',metric(t,'margin'),'Ponderato sui ricavi del mese')+kpi('Prodotti sotto scorta',low.length,'Varianti attive alla soglia o esaurite');
 $('fiscal-note').textContent='Risultati mensili dalle vendite registrate, prima dei resi. Utile prima degli altri oneri; basi IVA non confrontabili separate. I prezzi già salvati restano invariati. Nuovi prezzi suggeriti: pubblico −20%, ai €0,50 più vicini.';
 $('overview-low').innerHTML=low.slice(0,4).map(x=>`<div class="activity-row"><div>${productText(x.v.id)}</div><span class="stock-badge ${x.stock<=0?'out':'low'}">${x.stock} disponibili</span></div>`).join('')||empty('Tutte le scorte sono sopra la soglia.');
 $('recent-activity').innerHTML=[...data.movements].sort((a,b)=>Date.parse(b.occurred_at)-Date.parse(a.occurred_at)).slice(0,5).map(m=>`<div class="activity-row"><div>${productText(m.variant_id)}<small>${esc(date(m.occurred_at))}</small></div><span>${esc(labels[m.kind]||m.kind)}<strong>${Number(m.quantity)>0?'+':''}${Number(m.quantity)}</strong></span></div>`).join('')||empty('Nessuna attività registrata.');
}
function products(){
 const query=$('inventory-search').value.trim().toLocaleLowerCase('it');const rows=M.products(data).filter(x=>[x.p.name,x.p.brand,x.v.label,x.v.format,x.v.sku,x.v.ean].join(' ').toLocaleLowerCase('it').includes(query));
 $('product-count').textContent=rows.length+' varianti';
 $('inventory-rows').innerHTML=rows.map(x=>{const {p,v,i,price,stock}=x;const sale=pricing.base(pricing.sale(price),price),cost=i.average_cost==null?null:Number(i.average_cost),profit=sale==null||cost==null?null:sale-cost;
 const state=!x.active?'Archiviato':p.status==='draft'?'Da verificare':stock<=0?'Esaurito':x.low?'Scorta bassa':'Disponibile';
 return `<article class="stock-card"><div class="stock-card-head"><div class="stock-photo">${image(v.image_url||p.image_url,p.name,'',p.image_scale)||'<span>Foto non disponibile</span>'}</div><div><small class="eyebrow">${esc(p.brand)}</small><h3>${esc(p.name)}</h3><p>${esc(v.label)} · ${esc(v.format)}</p><span class="stock-badge ${!x.active?'':stock<=0?'out':x.low?'low':''}">${state}</span></div></div><dl class="stock-metrics"><div><dt>Disponibili</dt><dd>${stock}</dd></div><div><dt>Costo medio</dt><dd>${euro(cost)}</dd></div><div><dt>Pubblico · IVA incl.</dt><dd>${euro(pricing.gross(price.public_price,price))}</dd></div><div><dt>NEACEA · IVA incl.</dt><dd>${saleEuro(pricing.sale(price))}</dd></div><div><dt>Utile unitario</dt><dd>${euro(profit)}</dd></div><div><dt>Margine</dt><dd>${percent(sale>0&&profit!=null?profit/sale*100:null)}</dd></div></dl><p class="muted">Costo e utile: ${esc(basis(price.tax_basis))}</p><div class="actions"><button class="primary" data-sell="${esc(v.id)}" ${!x.active||stock<=0?'disabled':''}>Vendi</button><button data-move="${esc(v.id)}">Movimento</button></div><details><summary>Dettaglio e gestione</summary><dl class="detail-list"><dt>SKU / EAN</dt><dd>${esc(v.sku||'—')} / ${esc(v.ean||'—')}</dd><dt>Soglia riordino</dt><dd>${x.threshold}</dd><dt>Ricevuti</dt><dd>${Number(i.purchased_units||0)} acquistati · ${Number(i.sample_units||0)} campioni</dd><dt>Media acquisti</dt><dd>${Number(i.purchased_units)?euro(i.purchase_average_cost):'—'}</dd></dl><div class="actions"><button data-edit="${esc(p.id)}">Modifica</button><button data-enrich="${esc(v.id)}">Importa scheda</button><button data-publish="${esc(v.id)}">Pubblica</button></div></details></article>`;
 }).join('')||empty('Nessun prodotto corrisponde alla ricerca.');
}
function sales(){
 const range=M.period(salePeriod,new Date(),$('sale-from').value,$('sale-to').value);
 document.querySelectorAll('[data-period]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.period===salePeriod)));$('custom-range').hidden=salePeriod!=='custom';
 if(salePeriod==='custom'&&(!range.from||!range.to||range.from>range.to)){$('sales-range-label').textContent='Seleziona entrambe le date; la data finale deve essere uguale o successiva a quella iniziale.';$('sales-kpis').innerHTML='';$('sales-history').innerHTML='';$('top-products').innerHTML='';return;}
 $('sales-range-label').textContent=`Dal ${range.from.split('-').reverse().join('/')} al ${range.to.split('-').reverse().join('/')} · fuso orario Italia`;
 const rows=M.sales(data.movements,range),t=M.totals(rows);salePage=Math.min(salePage,Math.max(0,Math.ceil(rows.length/20)-1));
 $('sales-kpis').innerHTML=kpi('Incasso totale',euro(t.receipt),'IVA inclusa')+kpi('Costo del venduto',metric(t,'cost'))+kpi('Utile lordo',metric(t,'profit'))+kpi('Margine medio',metric(t,'margin'))+kpi('Pezzi venduti',t.units)+kpi('Numero vendite',t.count,'Un movimento SALE = una vendita');
 $('sales-history').innerHTML=rows.length?`<div class="table-wrap sales-table" tabindex="0" role="region" aria-label="Storico vendite, scorrimento orizzontale"><table><caption>Storico vendite · ${rows.length} registrazioni</caption><thead><tr>${['Data / ora','Prodotto / variante','Quantità','Prezzo unitario IVA incl.','Totale IVA incl.','Costo','Utile €','Margine %','Operatore',''].map(x=>`<th scope="col">${x}</th>`).join('')}</tr></thead><tbody>${rows.slice(salePage*20,salePage*20+20).map(m=>{const f=M.finance(m);return `<tr><td>${esc(date(m.occurred_at))}</td><td>${productText(m.variant_id)}</td><td>${f.qty}</td><td>${euro(f.receipt==null?null:f.receipt/f.qty)}</td><td>${euro(f.receipt)}</td><td>${euro(f.cost)}<small>${esc(basis(f.basis))}</small></td><td>${euro(f.profit)}</td><td>${percent(f.margin)}</td><td>${esc(operator(m.created_by))}</td><td><button data-return="${esc(m.id)}">Reso</button></td></tr>`;}).join('')}</tbody></table></div>${paginate(rows,salePage,'sale')}`:empty('Nessuna vendita nel periodo selezionato.');
 const top=M.ranking(rows,$('ranking-sort').value);$('top-products').innerHTML=top.map((r,n)=>`<div class="ranking-row"><span class="rank-number">${n+1}</span><div>${productText(r.id)}</div><div><small>Quantità</small><strong>${r.qty}</strong></div><div><small>Fatturato IVA incl.</small><strong>${euro(r.receipt)}</strong></div><div><small>Utile</small><strong>${esc(metric(r,'profit'))}</strong></div></div>`).join('')||empty('I prodotti più venduti compariranno dopo la prima vendita.');
}
function movements(){
 const range={from:$('movement-from').value,to:$('movement-to').value};if(range.from&&range.to&&range.from>range.to){$('movement-count').textContent='La data finale precede quella iniziale.';$('movements').innerHTML='';return;}
 const query=$('movement-search').value.toLocaleLowerCase('it'),kind=$('movement-kind').value;
 const rows=data.movements.filter(m=>{const {p,v}=lookup(m.variant_id);return (!kind||m.kind===kind)&&M.within(m,range)&&[p.name,v.label,m.document_ref,m.lot,m.notes].join(' ').toLocaleLowerCase('it').includes(query);}).sort((a,b)=>Date.parse(b.occurred_at)-Date.parse(a.occurred_at));
 movePage=Math.min(movePage,Math.max(0,Math.ceil(rows.length/20)-1));$('movement-count').textContent=rows.length+' movimenti';
 $('movements').innerHTML=rows.slice(movePage*20,movePage*20+20).map(m=>`<article class="movement-card"><div><span class="stock-badge">${esc(labels[m.kind]||m.kind)}</span><strong>${Number(m.quantity)>0?'+':''}${Number(m.quantity)} confezioni</strong><small>${esc(date(m.occurred_at))}</small></div><div>${productText(m.variant_id)}<small>${esc(m.document_ref)} ${esc(m.lot)}</small></div><div>Costo unitario ${euro(m.unit_cost)}<small>${esc(basis(m.tax_basis))}</small>${m.sale_price!=null?`<span>Vendita unit. ${saleEuro(m.tax_basis==='net'&&m.vat_rate==null?null:pricing.gross(m.sale_price,m))} IVA incl.</span>`:''}<small>Operatore: ${esc(operator(m.created_by))}</small></div><div><p>${esc(m.notes)}</p>${m.kind==='SALE'?`<button data-return="${esc(m.id)}">Reso</button>`:''}</div></article>`).join('')||empty('Nessun movimento per questi filtri.');$('movements').insertAdjacentHTML('beforeend',paginate(rows,movePage,'move'));
 $('documents').innerHTML=data.documents.map(doc=>`<div class="ledger-row"><strong>${esc(doc.reference)}</strong><span>${esc(doc.status==='imported'?'Importato':'Da verificare')}</span><span>${doc.rows.length} righe</span>${doc.has_file?`<button data-original="${esc(doc.id)}">Scarica originale</button>`:''}${doc.status==='review'?`<button data-document="${esc(doc.id)}">Verifica e importa</button>`:''}</div>`).join('')||empty('Nessun documento caricato.');
}
function reorders(){const rows=M.products(data).filter(x=>x.low).sort((a,b)=>a.stock-b.stock||String(a.p.name).localeCompare(b.p.name));$('reorder-count').textContent=rows.length+' varianti da riordinare';$('reorder-list').innerHTML=rows.map(x=>`<article class="stock-card"><div class="stock-card-head"><div class="stock-photo">${image(x.v.image_url||x.p.image_url,x.p.name,'',x.p.image_scale)}</div><div>${productText(x.v.id,false)}<span class="stock-badge ${x.stock<=0?'out':'low'}">${x.stock<=0?'Esaurito':'Scorta bassa'}</span></div></div><dl class="stock-metrics"><div><dt>Stock attuale</dt><dd>${x.stock}</dd></div><div><dt>Soglia</dt><dd>${x.threshold}</dd></div><div><dt>Da riordinare</dt><dd>${x.suggested}</dd></div></dl><button data-move="${esc(x.v.id)}">Registra carico</button></article>`).join('')||empty('Nessun riordino necessario: tutte le scorte sono sopra la soglia.');}
$('warehouse-tabs').addEventListener('keydown',e=>{const current=tabs.indexOf(section);let next;if(e.key==='ArrowRight')next=tabs[(current+1)%tabs.length];if(e.key==='ArrowLeft')next=tabs[(current+tabs.length-1)%tabs.length];if(e.key==='Home')next=tabs[0];if(e.key==='End')next=tabs.at(-1);if(next){e.preventDefault();selectTab(next,true);}});
$('inventory').addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.section)selectTab(b.dataset.section);if(b.dataset.period){salePeriod=b.dataset.period;salePage=0;if(salePeriod==='custom'&&!$('sale-from').value){const p=M.period('month');$('sale-from').value=p.from;$('sale-to').value=p.to;}sales();}if(b.dataset.page){if(b.dataset.page==='sale'){salePage+=Number(b.dataset.delta);sales();}else{movePage+=Number(b.dataset.delta);movements();}}});
$('inventory-search').oninput=()=>products();for(const id of ['sale-from','sale-to','ranking-sort'])$(id).onchange=()=>{salePage=0;sales();};for(const id of ['movement-kind','movement-from','movement-to','movement-search'])$(id).addEventListener(id==='movement-search'?'input':'change',()=>{movePage=0;movements();});
return {render(d){data=d;overview();products();sales();movements();reorders();selectTab(section);},clear(){data=null;for(const id of ['kpis','inventory-rows','sales-kpis','sales-history','top-products','movements','documents','reorder-list','recent-activity','overview-low','reorder-count','movement-count','product-count','fiscal-note','sales-range-label'])$(id).replaceChildren();}};
};
