import assert from 'node:assert/strict';
import fs from 'node:fs';
import vm from 'node:vm';
import { createRequire } from 'node:module';
const { templateSnapshot } = createRequire(import.meta.url)('../../netlify/functions/lib/pt-templates');
import { build } from 'esbuild';
import { mkdtemp, rm } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { pathToFileURL, fileURLToPath } from 'node:url';
const temp = await mkdtemp(join(tmpdir(), 'pt-editor-test-'));
await build({entryPoints:[fileURLToPath(new URL('src/adapter.ts', import.meta.url))],bundle:true,format:'esm',outfile:join(temp,'adapter.mjs')});
const {toSnapshot,applySnapshot,duplicateDaySnapshot,copyProgramSnapshot} = await import(pathToFileURL(join(temp,'adapter.mjs')));
await rm(temp,{recursive:true,force:true});
const state={sessions:['W1','W2','W3','W4'],sheetOrder:['A'],currentSheet:'A',meta:{warmup:'Cyclette'},sheets:{A:[{id:'squat',name:'Squat',notes:'Tecnica',recovery:'90 sec',plan:['3 x 8','3 x 8','3 x 8','3 x 8'],feedback:['50','','',''],weekSets:Array.from({length:4},(_,week)=>Array.from({length:3},(_,i)=>({id:`set${i}`,reps:'8',load:week===0?'50':'',rir:'2',sessionNote:week===0?'OK':'',note:''})))}]}};
const uneven=structuredClone(state);
uneven.sheets.A[0].weekSets[0][1].reps='7'; uneven.sheets.A[0].weekSets[0][1].rir='1';
const unevenSnapshot=toSnapshot(uneven); unevenSnapshot.program.days[0].name='Seduta rinominata';
applySnapshot(uneven,unevenSnapshot);
assert.equal(uneven.sheets.A[0].weekSets[0][1].reps,'7'); assert.equal(uneven.sheets.A[0].weekSets[0][1].rir,'1');
let snap=toSnapshot(state); applySnapshot(state,snap);
assert.equal(state.sheets.A[0].weekSets[0][0].load,'50');
assert.equal(state.sheets.A[0].weekSets[0][0].sessionNote,'OK');
snap=toSnapshot(state);snap.program.days[0].exercisesByWeek[2][0].reps='12';
snap.program.days[0].groupsByWeek[2]=[{key:'g1',type:'superset',exerciseKeys:['squat','row'],rounds:'3',restBetweenRounds:'90 sec',note:'Alternare'}];
snap.program.days[0].exercisesByWeek[2].push({...snap.program.days[0].exercisesByWeek[2][0],key:'row',name:'Rematore'});
applySnapshot(state,snap);
assert.equal(state.sheets.A[0].weekSets[0][0].reps,'8');assert.equal(state.sheets.A[0].weekSets[1][0].reps,'12');
assert.deepEqual(state.sheets.A[1].coachingActiveWeeks,[2]);
assert.equal(toSnapshot(state).program.days[0].groupsByWeek[2][0].note,'Alternare');
state.sheets.A[0].weekSets[0][0].load='60';
assert.equal(toSnapshot(state).program.days[0].exercisesByWeek[1][0].reps,'8');
snap=toSnapshot(state);snap.program.days[0].name='Gambe';applySnapshot(state,snap);
assert.equal(state.sheets.A[0].weekSets[0][0].load,'60');
assert.equal(JSON.parse(JSON.stringify(state)).coachingEditorSnapshot.program.days[0].name,'Gambe');
snap=toSnapshot(state);snap.program.days[0].exercisesByWeek[1][0].sets='2';applySnapshot(state,snap);
snap=toSnapshot(state);snap.program.days[0].exercisesByWeek[1][0].sets='3';applySnapshot(state,snap);
assert.equal(state.sheets.A[0].weekSets[0][2].load,'50');
const long={...state,sessions:Array.from({length:12},(_,i)=>`W${i+1}`)};assert.equal(toSnapshot(long).program.weeks.length,12);
const beforeCopy=structuredClone(state);
const performance = structuredClone(state);
const prescribed = toSnapshot(performance).program.days[0].exercisesByWeek[1][0];
performance.sheets.A[0].weekSets[0][0].reps = '5';
performance.sheets.A[0].weekSets[0][0].rir = '0';
assert.equal(toSnapshot(performance).program.days[0].exercisesByWeek[1][0].reps, prescribed.reps, 'actual repetitions must not rewrite the archived prescription');
assert.equal(toSnapshot(performance).program.days[0].exercisesByWeek[1][0].rir, prescribed.rir, 'actual RIR must not rewrite the archived prescription');
const revised = toSnapshot(performance);
revised.program.days[0].exercisesByWeek[1][0].reps = '12';
applySnapshot(performance, revised);
assert.equal(performance.sheets.A[0].weekSets[0][0].reps, '5', 'editing a prescription must preserve a recorded performance');
assert.equal(performance.sheets.A[0].weekSets[0][0].rir, '0');
performance.meta.level = 'Avanzato'; performance.meta.frequency = '3 volte'; performance.meta.warmup = 'Nuovo riscaldamento';
assert.equal(toSnapshot(performance).program.settings.warmup, 'Nuovo riscaldamento');
console.log('Archive fidelity: actual performance separate from prescription; general settings preserved.');
const portal = fs.readFileSync(new URL('../../app/portale-personal-trainer/index.html', import.meta.url), 'utf8');
const monthBody = portal.slice(portal.indexOf('    async function newMonthFromCurrent()'), portal.indexOf('    function applyProgramMutation('));
let nextMonth;
const monthContext = vm.createContext({ state: performance, selectedClient: () => ({}), fullName: () => 'Test',
  confirmAction: async () => true, ensureCurrentProgramSaved: async () => true, normalizeState: structuredClone,
  clone: structuredClone, appState: {selectedProgramId:'old'}, currentPeriodKey: () => '2026-09', nextPeriodKey: () => '2026-10',
  periodLabel: p => p, ensureExerciseWeekSets() {}, normalizeSetEntry: s => s, syncExerciseWeekSummary() {},
  window: { NeaceaPTEditor: { applySnapshot, toSnapshot } }, createAndPersistProgram: async s => {nextMonth=s;} });
vm.runInContext(monthBody, monthContext);
await monthContext.newMonthFromCurrent();
assert.equal(nextMonth.sheets.A[0].weekSets[0][0].reps, '12');
assert.equal(nextMonth.sheets.A[0].weekSets[0][0].load, '');
assert.equal(nextMonth.sheets.A[0].weekSets[0][0].previousLoad, '60');
assert.equal(nextMonth.sheets.A[0].weekSets[0][0].recorded, false);
assert.equal(nextMonth.sheets.A[0].weekSets[0][0].sessionNote, '');
console.log('Next month starts with prescribed values, preserves previous load only as a reference.');
const cleanModel = templateSnapshot(toSnapshot(performance), 'Confronto integrale');
const assigned = { sessions: cleanModel.program.weeks.map(w => `W${w}`), sheets: {}, sheetOrder: [], currentSheet: 'A', meta: { ...cleanModel.program.settings, name: 'Confronto integrale' }, workoutDates: {} };
applySnapshot(assigned, copyProgramSnapshot(cleanModel, 'Confronto integrale', p => `${p}-${Math.random()}`));
assert.deepEqual(templateSnapshot(toSnapshot(assigned), 'Confronto integrale'), cleanModel, 'every prescription and setting must survive archive -> assignment -> reopen');
assert.ok(assigned.sheets.A.every(e=>e.weekSets.flat().every(s=>!s.load&&!s.sessionNote&&!s.previousLoad)));
console.log('Full archive round-trip equality: settings, every week, notes and groups preserved.');
let nextId=0;
state.meta.name = 'Forza base';
assert.equal(toSnapshot(state).program.title, 'Forza base');
const sourceSnapshot = toSnapshot(state), sourceBefore = JSON.stringify(sourceSnapshot);
const programCopy = copyProgramSnapshot(sourceSnapshot, 'Nuovo ciclo forza', prefix => `${prefix}-new-${++nextId}`);
assert.equal(JSON.stringify(sourceSnapshot), sourceBefore, 'copy never mutates original');
assert.equal(programCopy.program.title, 'Nuovo ciclo forza');
assert.notEqual(programCopy.program.sourceId, sourceSnapshot.program.sourceId);
assert.notEqual(programCopy.program.days[0].key, sourceSnapshot.program.days[0].key);
assert.notEqual(programCopy.program.days[0].exercisesByWeek[1][0].key, sourceSnapshot.program.days[0].exercisesByWeek[1][0].key);
const fresh = { sessions: [...state.sessions], sheetOrder: [], sheets: {}, meta: {name:'Nuovo ciclo forza'}, currentSheet: 'A' };
applySnapshot(fresh, programCopy);
assert.ok(Object.values(fresh.sheets).flat().every(e => e.weekSets.flat().every(s => !s.load && !s.sessionNote && !s.previousLoad)));
assert.ok(fresh.coachingEditorSnapshot.program.days[0].groupsByWeek[2][0].exerciseKeys.every(k => fresh.sheets.A.some(e => e.id === k)));
assert.equal(JSON.parse(JSON.stringify(fresh)).meta.name, 'Nuovo ciclo forza');
delete state.meta.name;
console.log('Named whole-program copy: independent IDs, groups intact, no session history, original unchanged.');
const copied=duplicateDaySnapshot(state,'B',prefix=>`${prefix}-copy-${++nextId}`);
assert.deepEqual(state,beforeCopy);
applySnapshot(state,copied);
assert.equal(state.sheets.A[0].weekSets[0][0].load,'60');
assert.equal(state.sheets.B[0].weekSets[0][0].load,'');
assert.equal(state.sheets.B[0].weekSets[0][0].sessionNote,'');
assert.notEqual(state.sheets.B[0].id,state.sheets.A[0].id);
assert.equal(state.coachingEditorSnapshot.program.days[1].groupsByWeek[2][0].note,'Alternare');
assert.ok(state.coachingEditorSnapshot.program.days[1].groupsByWeek[2][0].exerciseKeys.every(key=>state.sheets.B.some(ex=>ex.id===key)));
assert.deepEqual(state.sheets.B[1].coachingActiveWeeks,[2]);
console.log('Day duplication: full prescription and groups preserved, independent IDs, no session records copied.');
snap=toSnapshot(state);snap.program.days=[];applySnapshot(state,snap);assert.deepEqual(state.sheetOrder,[]);
console.log('Adapter: legacy migration, weekly prescriptions, groups, loads, retired sets, 12 weeks and clear passed.');
// Forward-only inheritance, distinct from operational results.
const tempForward=await mkdtemp(join(tmpdir(),'pt-forward-test-'));
await build({entryPoints:[fileURLToPath(new URL('src/forward-weeks.ts',import.meta.url))],bundle:true,format:'esm',outfile:join(tempForward,'forward.mjs')});
const {propagateForward}=await import(pathToFileURL(join(tempForward,'forward.mjs')));
await build({entryPoints:[fileURLToPath(new URL('src/adapter.ts',import.meta.url))],bundle:true,format:'esm',outfile:join(tempForward,'adapter.mjs')});
const {inheritLegacyWeeks}=await import(pathToFileURL(join(tempForward,'adapter.mjs')));
const before={weeks:[1,2,3,4],days:[{key:'a',letter:'A',exercisesByWeek:{1:[],2:[],3:[],4:[]},groupsByWeek:{1:[],2:[],3:[],4:[]}}]};
let after=structuredClone(before);after.days[0].exercisesByWeek[1]=[{key:'e',name:'Squat',sets:'3',reps:'8'}];
propagateForward(before,after,1);assert.deepEqual(after.days[0].exercisesByWeek[4],after.days[0].exercisesByWeek[1]);
let previous=structuredClone(after);after.days[0].exercisesByWeek[3][0].reps='12';propagateForward(previous,after,3);
assert.equal(after.days[0].exercisesByWeek[2][0].reps,'8');assert.equal(after.days[0].exercisesByWeek[4][0].reps,'12');
previous=structuredClone(after);after.days[0].exercisesByWeek[3]=[];propagateForward(previous,after,3);
assert.equal(after.days[0].exercisesByWeek[4].length,0);assert.equal(after.days[0].exercisesByWeek[1].length,1);
const legacyForward={sessions:['W1','W2','W3','W4'],sheetOrder:['A'],currentSheet:'A',meta:{},sheets:{A:[{id:'e',name:'Squat',notes:'',recovery:'60',coachingActiveWeeks:[1],weekSets:[[{id:'s',reps:'8',load:'50',sessionNote:'done'}],[],[],[]],feedback:[]}]}};
inheritLegacyWeeks(legacyForward);
assert.deepEqual(legacyForward.sheets.A[0].coachingActiveWeeks,[1,2,3,4]);
assert.equal(legacyForward.sheets.A[0].weekSets[0][0].load,'50');assert.equal(legacyForward.sheets.A[0].weekSets[1][0].load,'');assert.equal(legacyForward.sheets.A[0].weekSets[1][0].sessionNote,'');
const unchanged=JSON.stringify(legacyForward);inheritLegacyWeeks(legacyForward);assert.equal(JSON.stringify(legacyForward),unchanged);
await rm(tempForward,{recursive:true,force:true});
console.log('Forward weeks: add, edit from week 3, remove, legacy hydration and performance isolation passed.');
